// src/views/CombosView.vue
<template>
  <div class="page">
    <div class="page__header">
      <h2 class="md-typescale-headline-medium page__title">{{ t('combos.title') }}</h2>
      <md-filled-button @click="$router.push('/combos/new')">
        <MdiIcon :path="mdiPlus" slot="icon" />
        {{ t('combos.add') }}
      </md-filled-button>
    </div>

    <div v-if="loading" class="empty-state">
      <md-circular-progress indeterminate></md-circular-progress>
    </div>

    <div v-else-if="!combos.length" class="empty-state">
      <MdiIcon :path="mdiSetMerge" class="empty-state__icon" />
      <p class="md-typescale-body-large">{{ t('common.empty') }}</p>
    </div>

    <div v-else>
      <div class="card-grid">
        <article v-for="c in combos" :key="c.id" class="card">
          <span class="card__avatar"><MdiIcon :path="mdiSetMerge" /></span>
          <div class="card__body">
            <h3 class="md-typescale-title-medium card__name">
              <span class="card__name-text" :title="c.name">{{ c.name }}</span>
              <span
                v-if="!c.enabled"
                class="card__disabled"
              >{{ t('combos.disabled') }}</span>
            </h3>
            <div v-if="c.members.length" class="card__members">
              <span
                v-for="(m, i) in c.members"
                :key="m"
                class="member-chip"
                :title="t('combos.member_order', { pos: i + 1 })"
              >
                {{ i + 1 }}. {{ m }}
              </span>
            </div>
          </div>
          <div class="card__actions">
            <md-icon-button
              :id="'combo-btn-' + c.id"
              class="card__more-btn"
              @click="toggleMenu(c)"
            >
              <MdiIcon :path="mdiDotsVertical" />
            </md-icon-button>
          </div>
        </article>
      </div>
    </div>

    <!-- Shared action menu (single instance, re-anchors per card) -->
    <md-menu
      :open="menuOpen != null"
      :anchor="menuAnchor"
      positioning="fixed"
      @closed="menuOpen = null"
    >
      <md-menu-item @click="editFromMenu">
        <MdiIcon :path="mdiPencilOutline" /> {{ t('common.edit') }}
      </md-menu-item>
      <md-menu-item class="menu-item--danger" @click="deleteFromMenu">
        <MdiIcon :path="mdiDeleteOutline" /> {{ t('common.delete') }}
      </md-menu-item>
    </md-menu>

    <md-dialog :open="deleteOpen" @close="deleteOpen = false">
      <div slot="headline">{{ t('combos.delete_title') }}</div>
      <div slot="content" class="form">
        <p class="md-typescale-body-medium">{{ t('combos.delete_confirm', { name: deleteTarget?.name || '' }) }}</p>
      </div>
      <div slot="actions">
        <md-text-button @click="deleteOpen = false">{{ t('common.cancel') }}</md-text-button>
        <md-text-button class="confirm-del" @click="confirmDelete">{{ t('combos.delete_confirm_btn') }}</md-text-button>
      </div>
    </md-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import '@material/web/iconbutton/icon-button.js';
import '@material/web/menu/menu.js';
import '@material/web/menu/menu-item.js';
import '@material/web/progress/circular-progress.js';
import { useRouter } from 'vue-router';
import { mdiPlus, mdiSetMerge, mdiDotsVertical, mdiPencilOutline, mdiDeleteOutline } from '@mdi/js';
import { combosApi, type Combo } from '../api';
import { t } from '../i18n';
import MdiIcon from '../components/MdiIcon.vue';

const router = useRouter();

const combos = ref<Combo[]>([]);
const loading = ref(true);
const deleteOpen = ref(false);
const deleteTarget = ref<Combo | null>(null);
const menuOpen = ref<string | null>(null);
const menuAnchor = ref('');
const menuTarget = ref<Combo | null>(null);

function toggleMenu(c: Combo) {
  if (menuOpen.value === c.id) {
    menuOpen.value = null;
  } else {
    menuTarget.value = c;
    menuAnchor.value = 'combo-btn-' + c.id;
    menuOpen.value = c.id;
  }
}

function editFromMenu() {
  if (menuTarget.value) {
    router.push(`/combos/${menuTarget.value.id}/edit`);
  }
}

function deleteFromMenu() {
  if (menuTarget.value) {
    deleteTarget.value = menuTarget.value;
    deleteOpen.value = true;
  }
}

async function confirmDelete() {
  if (!deleteTarget.value) return;
  try {
    await combosApi.delete(deleteTarget.value.id);
  } catch (e: any) {
    alert(t('combos.delete_failed', { msg: e?.message || e }));
  }
  deleteOpen.value = false;
  deleteTarget.value = null;
  await fetchCombos();
}

async function fetchCombos() {
  loading.value = true;
  try {
    combos.value = await combosApi.list();
  } catch {
    // 请求失败保持空列表
  } finally {
    loading.value = false;
  }
}

onMounted(fetchCombos);
</script>

<style scoped>
.page__header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 24px; gap: 16px; flex-wrap: wrap; }
.page__title { margin: 0; }
.empty-state { display: flex; flex-direction: column; align-items: center; gap: 8px; padding: 64px 24px; text-align: center; }
.empty-state__icon { font-size: 48px; color: var(--md-sys-color-on-surface-variant); }
.card-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(320px, 1fr)); gap: 16px; }
.card {
  background: var(--md-sys-color-surface-container-low); border-radius: var(--md-sys-shape-corner-medium);
  padding: 20px; display: grid; grid-template-columns: 44px 1fr auto; gap: 12px; align-items: start;
}
.card__avatar {
  width: 44px; height: 44px; border-radius: var(--md-sys-shape-corner-full);
  display: flex; align-items: center; justify-content: center;
  background: var(--md-sys-color-tertiary-container); color: var(--md-sys-color-on-tertiary-container);
}
.card__avatar svg { width: 22px; height: 22px; }
.card__body { display: flex; flex-direction: column; gap: 6px; min-width: 0; }
.card__name { margin: 0; display: flex; align-items: center; gap: 6px; min-width: 0; }
.card__name-text { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; min-width: 0; }
.card__disabled {
  display: inline-flex; align-items: center; padding: 1px 8px; border-radius: var(--md-sys-shape-corner-full);
  background: var(--md-sys-color-surface-container-high);
  color: var(--md-sys-color-on-surface-variant);
  font-size: 0.75rem; font-weight: 500;
}
.card__members { display: flex; flex-wrap: wrap; gap: 4px; }
.member-chip {
  display: inline-flex; align-items: center; padding: 2px 10px;
  border-radius: var(--md-sys-shape-corner-full);
  background: var(--md-sys-color-secondary-container);
  color: var(--md-sys-color-on-secondary-container);
  font-size: 0.75rem; font-variant-numeric: tabular-nums;
}
.card__actions { display: flex; justify-content: flex-end; position: relative; }
.card__more-btn { --md-icon-button-icon-size: 20px; width: 36px; height: 36px; }
.form { min-width: 300px; }
.confirm-del { color: var(--md-sys-color-error); }
</style>

<!-- md-menu teleports to document root, so its styles must not be scoped -->
<style>
.menu-item--danger { --md-menu-item-label-text-color: var(--md-sys-color-error); color: var(--md-sys-color-error); }
</style>

// src/views/CombosView.tsx
import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router';
import { Plus, Inbox, MoreVertical, Pencil, Trash2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { useCombosStore } from '@/stores/combos';
import { combosApi, type Combo } from '@/lib/api';
import { useT } from '@/i18n';
import { cn } from '@/lib/utils';

interface ComboCardProps {
  combo: Combo;
  onEdit: () => void;
  onDelete: () => void;
}

function ComboCard({ combo, onEdit, onDelete }: ComboCardProps) {
  const t = useT();

  return (
    <article className="bg-muted rounded-lg p-5 grid grid-cols-[1fr_auto] gap-3 items-start cursor-default">
      <div className="flex flex-col gap-0.5 min-w-0">
        <div className="flex items-center gap-2">
          <h3 className="font-medium truncate" title={combo.name}>
            {combo.name}
          </h3>
          {!combo.enabled && (
            <span className="inline-flex items-center px-2 py-0.5 rounded-full text-xs font-medium bg-muted-foreground/20 text-muted-foreground">
              {t('combos.disabled')}
            </span>
          )}
        </div>
        <div className="flex flex-wrap gap-1 mt-2">
          {combo.members.map((member, idx) => (
            <span
              key={idx}
              className="inline-flex items-center gap-1 px-2 py-1 rounded-md bg-background border text-xs"
              title={t('combos.member_order', { pos: idx + 1 })}
            >
              <span className="font-mono">{member}</span>
            </span>
          ))}
        </div>
      </div>

      <DropdownMenu>
        <DropdownMenuTrigger asChild>
          <Button variant="ghost" size="icon" className="w-9 h-9">
            <MoreVertical className="w-5 h-5" />
          </Button>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end">
          <DropdownMenuItem onClick={onEdit}>
            <Pencil className="w-4 h-4 mr-2" />
            {t('common.edit')}
          </DropdownMenuItem>
          <DropdownMenuItem onClick={onDelete} className="text-destructive focus:text-destructive">
            <Trash2 className="w-4 h-4 mr-2" />
            {t('common.delete')}
          </DropdownMenuItem>
        </DropdownMenuContent>
      </DropdownMenu>
    </article>
  );
}

export function CombosView() {
  const t = useT();
  const navigate = useNavigate();
  const { combos, fetchCombos } = useCombosStore();

  const [loading, setLoading] = useState(true);
  const [deleteDialogOpen, setDeleteDialogOpen] = useState(false);
  const [deleteTarget, setDeleteTarget] = useState<Combo | null>(null);

  // Load data
  useEffect(() => {
    const load = async () => {
      setLoading(true);
      try {
        await fetchCombos();
      } finally {
        setLoading(false);
      }
    };
    load();
  }, []);

  const handleEdit = (combo: Combo) => {
    navigate(`/combos/${combo.id}/edit`);
  };

  const handleDelete = (combo: Combo) => {
    setDeleteTarget(combo);
    setDeleteDialogOpen(true);
  };

  const confirmDelete = async () => {
    if (!deleteTarget) return;
    await combosApi.delete(deleteTarget.id);
    setDeleteDialogOpen(false);
    setDeleteTarget(null);
    await fetchCombos();
  };

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-start gap-4 flex-wrap">
        <h2 className="text-3xl font-normal m-0">{t('combos.title')}</h2>
        <Button onClick={() => navigate('/combos/new')}>
          <Plus className="w-4 h-4 mr-2" />
          {t('combos.add')}
        </Button>
      </div>

      {loading ? (
        <div className="flex flex-col items-center justify-center py-16">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
        </div>
      ) : combos.length === 0 ? (
        <div className="flex flex-col items-center gap-2 py-16 text-center">
          <Inbox className="w-12 h-12 text-muted-foreground" />
          <p className="text-lg">{t('common.empty')}</p>
        </div>
      ) : (
        <div className="grid grid-cols-[repeat(auto-fill,minmax(320px,1fr))] gap-4">
          {combos.map((combo) => (
            <ComboCard
              key={combo.id}
              combo={combo}
              onEdit={() => handleEdit(combo)}
              onDelete={() => handleDelete(combo)}
            />
          ))}
        </div>
      )}

      <Dialog open={deleteDialogOpen} onOpenChange={setDeleteDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>{t('combos.delete_title')}</DialogTitle>
            <DialogDescription>
              {t('combos.delete_confirm', { name: deleteTarget?.name || '' })}
            </DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button variant="outline" onClick={() => setDeleteDialogOpen(false)}>
              {t('common.cancel')}
            </Button>
            <Button variant="destructive" onClick={confirmDelete}>
              {t('combos.delete_confirm_btn')}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}

export default CombosView;
