// src/views/KeysView.vue
<template>
  <div class="page">
    <div class="page__header">
      <h2 class="md-typescale-headline-medium page__title">{{ t('keys.title') }}</h2>
      <md-filled-button @click="openCreate">
        <MdiIcon :path="mdiPlus" slot="icon" />
        {{ t('keys.create') }}
      </md-filled-button>
    </div>

    <div v-if="loading" class="empty-state"><md-circular-progress indeterminate></md-circular-progress></div>

    <div v-else-if="!keys.length" class="empty-state">
      <MdiIcon :path="mdiInboxOutline" class="empty-state__icon" />
      <p class="md-typescale-body-large">{{ t('common.empty') }}</p>
    </div>

    <div v-else class="table-card">
      <table class="table">
        <thead>
          <tr class="md-typescale-label-large">
            <th>{{ t('keys.col_key') }}</th><th>{{ t('keys.col_models') }}</th><th>{{ t('keys.col_quota') }}</th><th>{{ t('keys.col_created') }}</th><th>{{ t('keys.col_updated') }}</th><th></th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="k in keys" :key="k.id" class="md-typescale-body-medium">
            <td class="key-cell mono" :title="k.name">{{ k.name || t('common.unnamed') }} ({{ k.key_masked }})</td>
            <td class="models-cell">
              <div class="models-inner">
                <span v-if="!k.allowed_models || !k.allowed_models.length" class="chip chip--all md-typescale-label-medium">{{ t('common.all') }}</span>
                <span v-for="m in (k.allowed_models || [])" :key="m" class="chip md-typescale-label-medium">{{ m }}</span>
              </div>
            </td>
            <td class="quota-cell">
              <div v-if="quotaLines(k).length" class="quota-lines">
                <span v-for="line in quotaLines(k)" :key="line.key" class="quota-line mono" :class="{ 'quota-line--over': line.over }">
                  {{ line.key }}: {{ line.percent.toFixed(0) }}% {{ line.resets_in }}
                </span>
              </div>
              <span v-else class="muted">-</span>
            </td>
            <td class="time-cell">{{ formatTime(k.created_at) }}</td>
            <td class="time-cell">{{ formatTime(k.updated_at) }}</td>
            <td class="actions-cell">
              <md-icon-button :id="'key-btn-' + k.id" @click="toggleMenu(k)">
                <MdiIcon :path="mdiDotsVertical" />
              </md-icon-button>
            </td>
          </tr>
        </tbody>
      </table>
    </div>

    <!-- Shared action menu (single instance, re-anchors per row) -->
    <md-menu
      :open="menuOpen != null"
      :anchor="menuAnchor"
      positioning="fixed"
      @closed="menuOpen = null"
    >
      <md-menu-item @click="renameFromMenu">
        <MdiIcon :path="mdiPencilOutline" /> {{ t('keys.rename') }}
      </md-menu-item>
      <md-menu-item @click="permFromMenu">
        <MdiIcon :path="mdiShieldOutline" /> {{ t('keys.edit_perm') }}
      </md-menu-item>
      <md-menu-item @click="quotaFromMenu">
        <MdiIcon :path="mdiTuneVariant" /> {{ t('keys.config_quota') }}
      </md-menu-item>
      <md-menu-item class="menu-item--danger" @click="deleteFromMenu">
        <MdiIcon :path="mdiDeleteOutline" /> {{ t('common.delete') }}
      </md-menu-item>
    </md-menu>

    <md-dialog :open="createOpen" @close="createOpen = false">
      <div slot="headline">{{ t('keys.create') }}</div>
      <div slot="content" class="form">
        <md-outlined-text-field :value="newName" :label="t('keys.rename_label')" class="field" @input="newName = ($event.target as HTMLInputElement).value"></md-outlined-text-field>
      </div>
      <div slot="actions">
        <md-text-button @click="createOpen = false">{{ t('common.cancel') }}</md-text-button>
        <md-filled-button @click="createKey">{{ t('common.create') }}</md-filled-button>
      </div>
    </md-dialog>

    <md-dialog :open="renameOpen" @close="renameOpen = false">
      <div slot="headline">{{ t('keys.rename_title') }}</div>
      <div slot="content" class="form">
        <md-outlined-text-field :value="renameName" :label="t('keys.rename_label')" class="field" @input="renameName = ($event.target as HTMLInputElement).value"></md-outlined-text-field>
      </div>
      <div slot="actions">
        <md-text-button @click="renameOpen = false">{{ t('common.cancel') }}</md-text-button>
        <md-filled-button @click="renameKey">{{ t('common.save') }}</md-filled-button>
      </div>
    </md-dialog>

    <md-dialog :open="!!newKeyPlain" @close="newKeyPlain = ''">
      <div slot="headline">{{ t('keys.created_once') }}</div>
      <div slot="content" class="form">
        <p class="warn md-typescale-body-medium"><MdiIcon :path="mdiAlert" />{{ t('keys.save_warning') }}</p>
        <p class="md-typescale-body-medium deploy-label">{{ t('keys.plain_key') }}</p>
        <div class="key-box mono md-typescale-body-large">{{ newKeyPlain }}</div>
        <template v-if="deployLink">
          <p class="md-typescale-body-medium deploy-label">{{ t('keys.deploy_link') }}</p>
          <div class="key-box mono md-typescale-body-medium deploy-box">{{ deployLink }}</div>
        </template>
      </div>
      <div slot="actions">
        <md-text-button @click="copyKey"><MdiIcon :path="mdiContentCopy" slot="icon" />{{ t('keys.copy_key') }}</md-text-button>
        <md-text-button :disabled="!deployLink" @click="copyDeployLink"><MdiIcon :path="mdiLinkVariant" slot="icon" />{{ t('keys.copy_deploy') }}</md-text-button>
        <md-filled-button @click="newKeyPlain = ''">{{ t('common.done') }}</md-filled-button>
      </div>
    </md-dialog>

    <md-dialog :open="permOpen" @close="permOpen = false">
      <div slot="headline">{{ t('keys.perm_title', { name: editingKey?.name || t('common.unnamed') }) }}</div>
      <div slot="content" class="form">
        <p class="md-typescale-body-medium perm-desc">{{ t('keys.perm_desc') }}</p>
        <md-circular-progress v-if="modelsLoading" indeterminate></md-circular-progress>
        <div v-else class="perm-list">
          <template v-for="p in providerModels" :key="p.name">
            <div class="perm-provider-label md-typescale-label-large">{{ p.name }}</div>
            <label v-for="m in p.models" :key="m" class="perm-item md-typescale-body-medium">
              <md-checkbox :checked="permSet.has(m)" @click="togglePerm(m)"></md-checkbox>
              {{ m }}
            </label>
          </template>
        </div>
        <p v-if="!allModels.length && !modelsLoading" class="md-typescale-body-medium">{{ t('keys.perm_no_models') }}</p>
      </div>
      <div slot="actions">
        <md-text-button @click="permOpen = false">{{ t('common.cancel') }}</md-text-button>
        <md-filled-button @click="savePerms">{{ t('common.save') }}</md-filled-button>
      </div>
    </md-dialog>

    <md-dialog :open="quotaOpen" @close="quotaOpen = false">
      <div slot="headline">{{ t('keys.quota_title', { name: quotaKey?.name || t('common.unnamed') }) }}</div>
      <div slot="content" class="form">
        <p class="md-typescale-body-medium quota-desc">{{ t('keys.quota_desc') }}</p>
        <md-outlined-text-field type="number" min="0" :label="t('keys.quota_5h_label')" class="field"
          :value="String(quota5h)" @input="quota5h = parseInt(($event.target as HTMLInputElement).value || '0', 10)">
        </md-outlined-text-field>
        <div class="quota-preview mono md-typescale-body-medium">{{ t('keys.quota_preview', { value: formatAbbrev(quota5h) }) }}</div>
        <md-outlined-text-field type="number" min="0" :label="t('keys.quota_7d_label')" class="field"
          :value="String(quota7d)" @input="quota7d = parseInt(($event.target as HTMLInputElement).value || '0', 10)">
        </md-outlined-text-field>
        <div class="quota-preview mono md-typescale-body-medium">{{ t('keys.quota_preview', { value: formatAbbrev(quota7d) }) }}</div>
      </div>
      <div slot="actions">
        <md-text-button @click="quotaOpen = false">{{ t('common.cancel') }}</md-text-button>
        <md-filled-button @click="saveQuota">{{ t('common.save') }}</md-filled-button>
      </div>
    </md-dialog>

    <md-dialog :open="deleteOpen" @close="deleteOpen = false">
      <div slot="headline">{{ t('keys.delete_title') }}</div>
      <div slot="content" class="form">
        <p class="md-typescale-body-medium">{{ t('keys.delete_confirm', { name: deleteTarget?.name || t('common.unnamed') }) }}</p>
      </div>
      <div slot="actions">
        <md-text-button @click="deleteOpen = false">{{ t('common.cancel') }}</md-text-button>
        <md-text-button class="confirm-del" @click="confirmDelete">{{ t('keys.delete_confirm_btn') }}</md-text-button>
      </div>
    </md-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch, onMounted, onUnmounted } from 'vue';
import '@material/web/iconbutton/icon-button.js';
import '@material/web/menu/menu.js';
import '@material/web/menu/menu-item.js';
import '@material/web/textfield/outlined-text-field.js';
import '@material/web/checkbox/checkbox.js';
import '@material/web/progress/circular-progress.js';
import {
  mdiPlus, mdiInboxOutline, mdiDotsVertical, mdiPencilOutline,
  mdiShieldOutline, mdiTuneVariant, mdiDeleteOutline, mdiAlert,
  mdiContentCopy, mdiLinkVariant,
} from '@mdi/js';
import { serviceKeysApi, providersApi, modelsApi, combosApi, installApi, type ServiceKey } from '../api';
import { wsClient } from '../ws';
import { t } from '../i18n';
import MdiIcon from '../components/MdiIcon.vue';

type KeyRow = ServiceKey & { used_5h?: number; used_7d?: number };

const keys = ref<KeyRow[]>([]);
const loading = ref(true);
const createOpen = ref(false);
const newName = ref('');
const newKeyPlain = ref('');
// 分发链接：本机 IP + 公共端口 + 明文 key。newKeyPlain 有值时拉取本机 IP。
const localIp = ref<string | null>(null);
const localPort = ref<number>(19068);
const deployLink = computed(() => {
  if (!newKeyPlain.value || !localIp.value) return '';
  return `http://${localIp.value}:${localPort.value}/install?t=${newKeyPlain.value}`;
});
watch(newKeyPlain, async (v) => {
  if (v && !localIp.value) {
    try {
      const r = await installApi.localIp();
      if (r.ip) localIp.value = r.ip;
      if (r.port) localPort.value = r.port;
    } catch {
      // 取不到 IP 时 deployLink 留空，仅显示明文 key
    }
  }
});

const permOpen = ref(false);
const editingKey = ref<ServiceKey | null>(null);
const permSet = ref<Set<string>>(new Set());
const allModels = ref<string[]>([]);
const providerModels = ref<{ name: string; models: string[] }[]>([]);
const modelsLoading = ref(false);

// 配置额度对话框
const quotaOpen = ref(false);
const quotaKey = ref<ServiceKey | null>(null);
const quota5h = ref(0);
const quota7d = ref(0);

// 共享操作菜单（单实例，按行重定向 anchor）
const menuOpen = ref<string | null>(null);
const menuAnchor = ref('');
const menuTarget = ref<ServiceKey | null>(null);
function toggleMenu(k: ServiceKey) {
  if (menuOpen.value === k.id) {
    menuOpen.value = null;
  } else {
    menuTarget.value = k;
    menuAnchor.value = 'key-btn-' + k.id;
    menuOpen.value = k.id;
  }
}
function renameFromMenu() {
  if (!menuTarget.value) return;
  editingKey.value = menuTarget.value;
  renameName.value = menuTarget.value.name || '';
  renameOpen.value = true;
}
function permFromMenu() {
  if (menuTarget.value) openPerms(menuTarget.value);
}
function quotaFromMenu() {
  if (!menuTarget.value) return;
  quotaKey.value = menuTarget.value;
  quota5h.value = menuTarget.value.quota_5h ?? 0;
  quota7d.value = menuTarget.value.quota_7d ?? 0;
  quotaOpen.value = true;
}
function deleteFromMenu() {
  if (menuTarget.value) openDeleteMenu(menuTarget.value);
}

/** 滚动窗口剩余时间（秒 → XdYh / XhYm），用于限额列与额度预览。 */
function resetsIn(remainingSecs: number): string {
  const r = Math.max(0, Math.floor(remainingSecs));
  const d = Math.floor(r / 86400);
  const h = Math.floor((r % 86400) / 3600);
  const m = Math.max(1, Math.floor((r % 3600) / 60));
  if (d > 0) return `${d}d${h}h`;
  if (h > 0) return `${h}h${m}m`;
  return `${m}m`;
}

/** 省略读数：≥1e8 → x.xx亿/B，≥1e4 → x.xx万/K，否则原样；0 → 不设限。 */
function formatAbbrev(n: number): string {
  if (!n || n <= 0) return t('keys.unlimited');
  if (n >= 1e8) return (n / 1e8).toFixed(2) + t('keys.unit_yi');
  if (n >= 1e4) return (n / 1e4).toFixed(2) + t('keys.unit_wan');
  return String(n);
}

/** 限额列的窗口行：未设限（quota<=0）的窗口不展示。 */
function quotaLines(k: KeyRow): { key: string; resets_in: string; percent: number; over: boolean }[] {
  const lines: { key: string; resets_in: string; percent: number; over: boolean }[] = [];
  const now = Math.floor(Date.now() / 1000);
  const push = (used: number, limit: number, label: string, windowSecs: number) => {
    if (!limit || limit <= 0) return;
    lines.push({
      key: label,
      resets_in: resetsIn(windowSecs - (now % windowSecs)),
      percent: (used / limit) * 100,
      over: used >= limit,
    });
  };
  push(k.used_5h ?? 0, k.quota_5h ?? 0, '5h', 5 * 3600);
  push(k.used_7d ?? 0, k.quota_7d ?? 0, '7d', 7 * 86400);
  return lines;
}

async function saveQuota() {
  if (!quotaKey.value) return;
  try {
    await serviceKeysApi.update(quotaKey.value.id, {
      quota_5h: quota5h.value,
      quota_7d: quota7d.value,
    });
    quotaOpen.value = false;
    await fetchKeys();
  } catch (e: any) {
    alert(t('keys.save_quota_failed', { msg: e?.message || e }));
  }
}

const renameOpen = ref(false);
const renameName = ref('');
async function renameKey() {
  if (!editingKey.value) return;
  try {
    await serviceKeysApi.update(editingKey.value.id, { name: renameName.value.trim() || t('common.unnamed') });
    renameOpen.value = false;
    await fetchKeys();
  } catch (e: any) {
    alert(t('keys.rename_failed', { msg: e?.message || e }));
  }
}

// 首次加载显示 spinner；后续刷新（WS 事件 / 轮询 / 增删改后）静默更新数据，
// 由 Vue diff 只改变化的单元格，避免整表闪 spinner 造成「强制刷新」观感。
const loaded = ref(false);
async function fetchKeys() {
  if (!loaded.value) loading.value = true; // 仅首次进入 loading
  try {
    keys.value = await serviceKeysApi.list();
    loaded.value = true;
  } finally {
    loading.value = false;
  }
}
function openCreate() { newName.value = ''; createOpen.value = true; }
async function createKey() {
  try {
    const r = await serviceKeysApi.create({ name: newName.value || t('common.unnamed') });
    createOpen.value = false;
    newKeyPlain.value = r.key;
    await fetchKeys();
  } catch (e: any) {
    alert(t('keys.create_failed', { msg: e?.message || e }));
  }
}
async function copyKey() { try { await navigator.clipboard.writeText(newKeyPlain.value); } catch {} }
async function copyDeployLink() {
  if (!deployLink.value) return;
  try { await navigator.clipboard.writeText(deployLink.value); } catch {}
}
const deleteOpen = ref(false);
const deleteTarget = ref<ServiceKey | null>(null);
function openDeleteMenu(k: ServiceKey) {
  deleteTarget.value = k;
  deleteOpen.value = true;
}
async function confirmDelete() {
  if (!deleteTarget.value) return;
  try {
    await serviceKeysApi.delete(deleteTarget.value.id);
    deleteOpen.value = false;
    deleteTarget.value = null;
    await fetchKeys();
  } catch (e: any) {
    alert(t('keys.delete_failed', { msg: e?.message || e }));
  }
}

function openPerms(k: ServiceKey) {
  editingKey.value = k;
  permSet.value = new Set(k.allowed_models || []);
  permOpen.value = true;
  fetchAvailableModels();
}

async function fetchAvailableModels() {
  modelsLoading.value = true;
  try {
    const [providers, models, combos] = await Promise.all([providersApi.list(), modelsApi.list(), combosApi.list()]);
    const providerName = new Map(providers.map((p) => [p.id, p.name]));
    const groupsMap = new Map<string, string[]>();
    for (const m of models) {
      const pname = providerName.get(m.provider_id) || t('common.unknown');
      const name = m.display_name || m.model_id;
      if (!groupsMap.has(pname)) groupsMap.set(pname, []);
      if (!groupsMap.get(pname)!.includes(name)) groupsMap.get(pname)!.push(name);
    }
    const groups = Array.from(groupsMap.entries()).map(([name, ms]) => ({ name, models: ms.sort() }));
    // 组合别名独立分组：授予组合名 = 授予其全部成员；只授予成员名则调用组合会被 403
    const comboGroup = combos.filter((c) => c.enabled).map((c) => c.name).sort();
    if (comboGroup.length) {
      groups.push({ name: t('keys.perm_group_combos'), models: comboGroup });
    }
    providerModels.value = groups;
    allModels.value = groups.flatMap((g) => g.models);
  } catch {} finally { modelsLoading.value = false; }
}

function togglePerm(model: string) {
  const s = new Set(permSet.value);
  s.has(model) ? s.delete(model) : s.add(model);
  permSet.value = s;
}

async function savePerms() {
  if (!editingKey.value) return;
  const models = [...permSet.value];
  try {
    await serviceKeysApi.update(editingKey.value.id, { name: editingKey.value.name || undefined, allowed_models: models });
    permOpen.value = false;
    await fetchKeys();
  } catch (e: any) {
    alert(t('keys.save_perm_failed', { msg: e?.message || e }));
  }
}

function formatTime(t: number): string { const d = new Date(t*1000); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')} ${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`; }

// 用量刷新策略：
// 1. 后端每 5s 通过 WS 广播 usage_stats_changed（每次代理请求写库后都会触发），
//    收到即重新拉取——用量百分比、剩余时间实时保持新鲜；
// 2. WS 断连/空闲时降级为 60s 兜底轮询，保证窗口重置等边界仍能收敛。
let refreshTimer: ReturnType<typeof setInterval> | null = null;
function onUsageChanged() {
  fetchKeys();
}
onMounted(() => {
  fetchKeys();
  wsClient.connect();
  wsClient.on('usage_stats_changed', onUsageChanged);
  refreshTimer = setInterval(fetchKeys, 60000);
});
onUnmounted(() => {
  wsClient.off('usage_stats_changed', onUsageChanged);
  if (refreshTimer) clearInterval(refreshTimer);
});
</script>

<style scoped>
.page__header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 24px; gap: 16px; flex-wrap: wrap; }
.page__title { margin: 0; }
.empty-state { display: flex; flex-direction: column; align-items: center; gap: 8px; padding: 64px 24px; text-align: center; }
.empty-state__icon { font-size: 48px; color: var(--md-sys-color-on-surface-variant); }
.table-card { background: var(--md-sys-color-surface-container-low); border-radius: var(--md-sys-shape-corner-medium); padding: 16px; overflow-x: auto; }
/* 内容完整展示：不截断、不换行，由内容自然撑开列宽；超宽时表格横向滚动。 */
.table { border-collapse: collapse; table-layout: auto; width: max-content; min-width: 100%; }
.table th { text-align: left; padding: 12px 16px; color: var(--md-sys-color-on-surface-variant); vertical-align: middle; white-space: nowrap; }
.table td { padding: 12px 16px; vertical-align: middle; white-space: nowrap; }
.table tr { border-bottom: 1px solid var(--md-sys-color-outline-variant); }
.table tr:last-child { border-bottom: none; }
.models-inner { display: inline-flex; flex-wrap: nowrap; gap: 4px 6px; align-items: center; vertical-align: middle; }
.quota-lines { display: flex; flex-direction: column; gap: 2px; }
.quota-line { font-size: 0.78rem; line-height: 1.5; color: var(--md-sys-color-on-surface-variant); }
.quota-line--over { color: var(--md-sys-color-error); font-weight: 500; }
.muted { color: var(--md-sys-color-on-surface-variant); }
.quota-desc { color: var(--md-sys-color-on-surface-variant); margin: 0; }
.quota-preview { color: var(--md-sys-color-on-surface-variant); font-size: 0.8rem; font-style: italic ; margin-top: -8px; }
.time-cell { color: var(--md-sys-color-on-surface-variant); }
/* 右侧按钮列固定：横向滚动时按钮始终可见（无阴影，保持简洁）。 */
.actions-cell { position: sticky; right: 0; background: var(--md-sys-color-surface-container-low); text-align: right; }
.mono { font-family: 'Roboto Mono', monospace; }
.chip { display: inline-flex; align-items: center; padding: 2px 8px; border-radius: var(--md-sys-shape-corner-small); background: var(--md-sys-color-primary-container); color: var(--md-sys-color-on-primary-container); font-size: 0.75rem; line-height: 1.4; }
.chip--all { background: var(--md-sys-color-surface-container-highest); color: var(--md-sys-color-on-surface-variant); }
.form { display: flex; flex-direction: column; gap: 16px; min-width: 360px; }
.field { width: 100%; }
.warn { display: flex; align-items: center; gap: 8px; color: var(--md-sys-color-on-error-container); background: var(--md-sys-color-error-container); padding: 12px; border-radius: var(--md-sys-shape-corner-small); margin: 0; }
.key-box { background: var(--md-sys-color-surface-container-high); padding: 16px; border-radius: var(--md-sys-shape-corner-medium); word-break: break-all; border: 1px solid var(--md-sys-color-outline-variant); }
.deploy-label { margin: 4px 0 0; color: var(--md-sys-color-on-surface-variant); }
.deploy-box { font-size: 0.75rem; }
.perm-desc { color: var(--md-sys-color-on-surface-variant); margin: 0; }
.perm-list { max-height: 300px; overflow-y: auto; display: flex; flex-direction: column; gap: 4px; }
.perm-provider-label { color: var(--md-sys-color-on-surface-variant); padding: 8px 0 4px; border-top: 1px solid var(--md-sys-color-outline-variant); margin-top: 4px; }
.perm-provider-label:first-child { border-top: none; margin-top: 0; }
.perm-item { display: flex; align-items: center; gap: 8px; cursor: pointer; padding: 6px 0 6px 8px; }
.perm-item md-checkbox { flex-shrink: 0; margin-top: -2px; }
</style>

<!-- md-menu teleports to document root, so its styles must not be scoped -->
<style>
.menu-item--danger { --md-menu-item-label-text-color: var(--md-sys-color-error); color: var(--md-sys-color-error); }
</style>

// src/views/KeysView.tsx
import { useState, useEffect, useMemo } from 'react';
import { Plus, Search, Copy, Check, Trash2, Pencil, Shield, Gauge, Key as KeyIcon, Loader2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { serviceKeysApi, providersApi, modelsApi, combosApi, installApi, type ServiceKey, type ServiceKeyUsage } from '@/lib/api';
import { useWebSocket } from '@/hooks/useWebSocket';
import { useT } from '@/i18n';
import { cn } from '@/lib/utils';

/**
 * 密钥页：管理本网关发放给客户端的 Service Key（不是上游供应商的密钥）。
 *
 * - 创建：网关生成明文密钥（仅此一次可见），附分发链接（LAN install 页 + key）。
 * - 权限：allowed_models 白名单（空 = 全部），按供应商分组 + 组合名分组。
 * - 额度：5h / 7d 滚动窗口 token 上限（0 = 不设限），列表实时显示已用量百分比
 *   与窗口剩余时间，触顶红色。
 * - 用量经 WS usage_stats_changed（后端每 5s 广播）实时刷新，60s 兜底轮询。
 */

type ServiceKeyRow = ServiceKey & ServiceKeyUsage;

/** 格式化时间戳为 YYYY-MM-DD HH:mm（本地时区）。 */
function formatTime(t: number): string {
  const d = new Date(t * 1000);
  const p = (n: number) => String(n).padStart(2, '0');
  return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())} ${p(d.getHours())}:${p(d.getMinutes())}`;
}

/** 滚窗剩余时间（秒 → XdYh / XhYm / Ym）。 */
function resetsIn(remainingSecs: number): string {
  const r = Math.max(0, Math.floor(remainingSecs));
  const d = Math.floor(r / 86400);
  const h = Math.floor((r % 86400) / 3600);
  const m = Math.max(1, Math.floor((r % 3600) / 60));
  if (d > 0) return `${d}d${h}h`;
  if (h > 0) return `${h}h${m}m`;
  return `${m}m`;
}

/** 省略读数：≥1e8 → 亿，≥1e4 → 万，0 → 不设限。 */
function formatAbbrev(n: number, t: (key: string) => string): string {
  if (!n || n <= 0) return t('keys.unlimited');
  if (n >= 1e8) return (n / 1e8).toFixed(2) + t('keys.unit_yi');
  if (n >= 1e4) return (n / 1e4).toFixed(2) + t('keys.unit_wan');
  return String(n);
}

/** 限额列窗口行：仅展示设了上限的窗口；used >= limit 视为触顶。 */
function quotaLines(k: ServiceKeyRow, t: (key: string) => string): { key: string; resets_in: string; percent: number; over: boolean }[] {
  const now = Math.floor(Date.now() / 1000);
  const lines: { key: string; resets_in: string; percent: number; over: boolean }[] = [];
  const push = (used: number, limit: number | undefined, label: string, windowSecs: number) => {
    if (!limit || limit <= 0) return;
    lines.push({
      key: label,
      resets_in: resetsIn(windowSecs - (now % windowSecs)),
      percent: (used / limit) * 100,
      over: used >= limit,
    });
  };
  push(k.used_5h ?? 0, k.quota_5h, '5h', 5 * 3600);
  push(k.used_7d ?? 0, k.quota_7d, '7d', 7 * 86400);
  return lines;
}

export function KeysView() {
  const t = useT();

  const [keys, setKeys] = useState<ServiceKeyRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState('');

  // Create
  const [createDialogOpen, setCreateDialogOpen] = useState(false);
  const [newName, setNewName] = useState('');
  const [creating, setCreating] = useState(false);
  const [createdKey, setCreatedKey] = useState<{ key: string; name: string } | null>(null);
  const [copied, setCopied] = useState(false);
  const [localIp, setLocalIp] = useState<string | null>(null);
  const [localPort, setLocalPort] = useState(19068);

  // Rename
  const [renameDialogOpen, setRenameDialogOpen] = useState(false);
  const [renameTarget, setRenameTarget] = useState<ServiceKeyRow | null>(null);
  const [renameName, setRenameName] = useState('');

  // Perm (allowed models)
  const [permDialogOpen, setPermDialogOpen] = useState(false);
  const [permTarget, setPermTarget] = useState<ServiceKeyRow | null>(null);
  const [permSet, setPermSet] = useState<Set<string>>(new Set());
  const [permGroups, setPermGroups] = useState<{ name: string; models: string[] }[]>([]);
  const [modelsLoading, setModelsLoading] = useState(false);

  // Quota
  const [quotaDialogOpen, setQuotaDialogOpen] = useState(false);
  const [quotaTarget, setQuotaTarget] = useState<ServiceKeyRow | null>(null);
  const [quota5h, setQuota5h] = useState('');
  const [quota7d, setQuota7d] = useState('');

  // Delete
  const [deleteDialogOpen, setDeleteDialogOpen] = useState(false);
  const [deleteTarget, setDeleteTarget] = useState<ServiceKeyRow | null>(null);
  const [saving, setSaving] = useState(false);

  /** 首次加载显示 spinner；后续刷新（WS / 轮询 / 增删改后）静默更新。 */
  async function fetchServiceKeys(silent = false) {
    if (!silent) setLoading(true);
    try {
      const list = await serviceKeysApi.list();
      setKeys(list);
    } finally {
      setLoading(false);
    }
  }

  // Live usage: WS（每 5s 广播）+ 60s 兜底轮询
  useWebSocket('usage_stats_changed', () => fetchServiceKeys(true));
  useEffect(() => {
    fetchServiceKeys();
    const timer = window.setInterval(() => fetchServiceKeys(true), 60000);
    return () => window.clearInterval(timer);
  }, []);

  // 分发链接：创建成功后拉取本机 LAN IP（取不到则仅展示明文）
  useEffect(() => {
    if (createdKey && !localIp) {
      installApi.localIp().then((r) => {
        if (r.ip) setLocalIp(r.ip);
        if (r.port) setLocalPort(r.port);
      });
    }
  }, [createdKey, localIp]);

  const deployLink = createdKey && localIp ? `http://${localIp}:${localPort}/install?t=${createdKey.key}` : '';

  // Filtered keys
  const filteredKeys = useMemo(() => {
    if (!searchQuery.trim()) return keys;
    const query = searchQuery.toLowerCase();
    return keys.filter(
      (k) => k.name.toLowerCase().includes(query) || k.key_masked.toLowerCase().includes(query)
    );
  }, [keys, searchQuery]);

  // ── Actions ────────────────────────────────────────────────────────────────

  const handleCreate = async () => {
    setCreating(true);
    try {
      const r = await serviceKeysApi.create({ name: newName.trim() || t('common.unnamed') });
      setCreatedKey({ key: r.key, name: r.name });
      setNewName('');
      await fetchServiceKeys(true);
    } catch (e: any) {
      console.error('Failed to create service key:', e);
    } finally {
      setCreating(false);
    }
  };

  const handleRename = async () => {
    if (!renameTarget) return;
    setSaving(true);
    try {
      await serviceKeysApi.update(renameTarget.id, { name: renameName.trim() || t('common.unnamed') });
      setRenameDialogOpen(false);
      await fetchServiceKeys(true);
    } catch (e: any) {
      console.error('Failed to rename service key:', e);
    } finally {
      setSaving(false);
    }
  };

  const openPerms = (k: ServiceKeyRow) => {
    setPermTarget(k);
    setPermSet(new Set(k.allowed_models || []));
    setPermDialogOpen(true);
    loadPermOptions();
  };

  async function loadPermOptions() {
    setModelsLoading(true);
    try {
      const [providers, models, combos] = await Promise.all([
        providersApi.list(),
        modelsApi.list(),
        combosApi.list(),
      ]);
      const providerName = new Map(providers.map((p) => [p.id, p.name]));
      const groupsMap = new Map<string, string[]>();
      for (const m of models) {
        const pname = providerName.get(m.provider_id) || t('common.unknown');
        const name = m.display_name || m.model_id;
        if (!groupsMap.has(pname)) groupsMap.set(pname, []);
        if (!groupsMap.get(pname)!.includes(name)) groupsMap.get(pname)!.push(name);
      }
      const groups = Array.from(groupsMap.entries()).map(([name, ms]) => ({ name, models: ms.sort() }));
      // 组合别名独立分组：授予组合名 = 授予其全部成员
      const comboGroup = combos.filter((c) => c.enabled).map((c) => c.name).sort();
      if (comboGroup.length) {
        groups.push({ name: t('keys.perm_group_combos'), models: comboGroup });
      }
      setPermGroups(groups);
    } finally {
      setModelsLoading(false);
    }
  }

  const togglePerm = (model: string) => {
    setPermSet((prev) => {
      const s = new Set(prev);
      s.has(model) ? s.delete(model) : s.add(model);
      return s;
    });
  };

  const handleSavePerms = async () => {
    if (!permTarget) return;
    setSaving(true);
    try {
      await serviceKeysApi.update(permTarget.id, { allowed_models: [...permSet] });
      setPermDialogOpen(false);
      await fetchServiceKeys(true);
    } catch (e: any) {
      console.error('Failed to save perms:', e);
    } finally {
      setSaving(false);
    }
  };

  const handleSaveQuota = async () => {
    if (!quotaTarget) return;
    setSaving(true);
    try {
      await serviceKeysApi.update(quotaTarget.id, {
        quota_5h: quota5h ? parseInt(quota5h, 10) : 0,
        quota_7d: quota7d ? parseInt(quota7d, 10) : 0,
      });
      setQuotaDialogOpen(false);
      await fetchServiceKeys(true);
    } catch (e: any) {
      console.error('Failed to save quota:', e);
    } finally {
      setSaving(false);
    }
  };

  const confirmDelete = async () => {
    if (!deleteTarget) return;
    try {
      await serviceKeysApi.delete(deleteTarget.id);
      setDeleteDialogOpen(false);
      setDeleteTarget(null);
      await fetchServiceKeys(true);
    } catch (e: any) {
      console.error('Failed to delete service key:', e);
    }
  };

  const copyToClipboard = async (text: string) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
      return true;
    } catch {
      return false;
    }
  };

  const chip = 'inline-flex items-center px-2 py-1 rounded-md bg-background border text-xs font-mono';

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex justify-between items-start gap-4 flex-wrap">
        <h2 className="text-3xl font-normal m-0">{t('keys.title')}</h2>
        <Button onClick={() => { setNewName(''); setCreateDialogOpen(true); }}>
          <Plus className="w-4 h-4 mr-2" />
          {t('keys.create')}
        </Button>
      </div>

      {/* Search */}
      <div className="relative flex-1 min-w-[200px] max-w-md">
        <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
        <input
          type="text"
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
          placeholder={t('keys.search')}
          className="w-full h-10 pl-10 pr-4 rounded-md border border-input bg-background text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
        />
      </div>

      {/* Keys list */}
      {loading ? (
        <div className="flex items-center justify-center py-16">
          <Loader2 className="w-6 h-6 animate-spin text-muted-foreground" />
        </div>
      ) : filteredKeys.length === 0 ? (
        <div className="flex flex-col items-center gap-2 py-16 text-center">
          <KeyIcon className="w-12 h-12 text-muted-foreground" />
          <p className="text-lg">{t('common.empty')}</p>
        </div>
      ) : (
        <div className="border rounded-lg overflow-x-auto">
          {/* 真 table 而非独立 grid：行与表头共享列轨道，确保每列表头与数据左对齐 */}
          <table className="w-full min-w-[820px] text-left">
            <thead>
              <tr className="bg-muted text-xs text-muted-foreground border-b border-border">
                <th className="px-4 py-2.5 font-normal">{t('keys.col_key')}</th>
                <th className="px-3 py-2.5 font-normal">{t('keys.col_models')}</th>
                <th className="px-3 py-2.5 font-normal">{t('keys.col_quota')}</th>
                <th className="px-3 py-2.5 font-normal text-right">{t('keys.col_times')}</th>
                <th className="w-9" />
              </tr>
            </thead>
            <tbody>
              {filteredKeys.map((k) => {
                const lines = quotaLines(k, t);
                return (
                  <tr key={k.id} className="border-b border-border last:border-b-0 hover:bg-muted/40">
                    {/* 密钥：备注名 + 掩码 */}
                    <td className="px-4 py-3">
                      <p className="font-medium truncate" title={k.name}>
                        {k.name || t('common.unnamed')}
                      </p>
                      <p className="text-xs text-muted-foreground font-mono truncate mt-0.5">{k.key_masked}</p>
                    </td>

                    {/* 可用模型：白名单 chips；空 = 全部 */}
                    <td className="px-3 py-3">
                      <div className="flex flex-wrap gap-1">
                        {!k.allowed_models || k.allowed_models.length === 0 ? (
                          <span className={chip}>{t('common.all')}</span>
                        ) : (
                          k.allowed_models.map((m) => (
                            <span key={m} className={chip}>{m}</span>
                          ))
                        )}
                      </div>
                    </td>

                    {/* 限额：各窗口 已用% + 剩余；未设限显示 - */}
                    <td className="px-3 py-3">
                      <div className="flex flex-col gap-0.5">
                        {lines.length === 0 ? (
                          <span className="text-muted-foreground">-</span>
                        ) : (
                          lines.map((l) => (
                            <span
                              key={l.key}
                              className={cn(
                                'font-mono text-xs text-muted-foreground whitespace-nowrap',
                                l.over && 'text-destructive font-medium'
                              )}
                            >
                              {l.key}: {l.percent.toFixed(0)}% {l.resets_in}
                            </span>
                          ))
                        )}
                      </div>
                    </td>

                    {/* 创建 / 修改时间（右对齐） */}
                    <td className="px-3 py-3 text-right text-xs text-muted-foreground whitespace-nowrap">
                      <p>{formatTime(k.created_at)}</p>
                      <p>{formatTime(k.updated_at)}</p>
                    </td>

                    {/* Actions */}
                    <td className="pr-3 align-middle">
                      <DropdownMenu>
                        <DropdownMenuTrigger asChild>
                          <Button variant="ghost" size="icon" className="w-9 h-9">
                            <Pencil className="w-4 h-4" />
                          </Button>
                        </DropdownMenuTrigger>
                        <DropdownMenuContent align="end">
                          <DropdownMenuItem onClick={() => { setRenameTarget(k); setRenameName(k.name || ''); setRenameDialogOpen(true); }}>
                            <Pencil className="w-4 h-4 mr-2" />
                            {t('keys.rename')}
                          </DropdownMenuItem>
                          <DropdownMenuItem onClick={() => openPerms(k)}>
                            <Shield className="w-4 h-4 mr-2" />
                            {t('keys.edit_perm')}
                          </DropdownMenuItem>
                          <DropdownMenuItem onClick={() => { setQuotaTarget(k); setQuota5h(k.quota_5h?.toString() || ''); setQuota7d(k.quota_7d?.toString() || ''); setQuotaDialogOpen(true); }}>
                            <Gauge className="w-4 h-4 mr-2" />
                            {t('keys.config_quota')}
                          </DropdownMenuItem>
                          <DropdownMenuItem onClick={() => { setDeleteTarget(k); setDeleteDialogOpen(true); }} className="text-destructive focus:text-destructive">
                            <Trash2 className="w-4 h-4 mr-2" />
                            {t('common.delete')}
                          </DropdownMenuItem>
                        </DropdownMenuContent>
                      </DropdownMenu>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}

      {/* Create dialog */}
      <Dialog
        open={createDialogOpen}
        onOpenChange={(open) => {
          setCreateDialogOpen(open);
          if (!open) {
            setCreatedKey(null);
            setCopied(false);
          }
        }}
      >
        <DialogContent>
          <DialogHeader>
            <DialogTitle>{t('keys.create')}</DialogTitle>
            <DialogDescription>{t('keys.perm_desc')}</DialogDescription>
          </DialogHeader>

          {createdKey ? (
            <div className="space-y-4">
              <div className="rounded-lg bg-green-500/10 border border-green-500/20 p-4">
                <p className="text-sm font-medium text-green-600 dark:text-green-400 mb-2">
                  {t('keys.created_once')}
                </p>
                <p className="text-xs text-muted-foreground mb-3">{t('keys.save_warning')}</p>
                <label className="text-xs font-medium">{t('keys.plain_key')}</label>
                <div className="flex gap-2 mt-1">
                  <input
                    type="text"
                    readOnly
                    value={createdKey.key}
                    className="flex-1 px-3 py-2 rounded-md border border-input bg-background text-sm font-mono"
                  />
                  <Button size="sm" onClick={() => copyToClipboard(createdKey.key)}>
                    {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                  </Button>
                </div>
                {deployLink && (
                  <>
                    <label className="text-xs font-medium mt-3 block">
                      {t('keys.deploy_link')}
                    </label>
                    <div className="flex gap-2 mt-1">
                      <input
                        type="text"
                        readOnly
                        value={deployLink}
                        className="flex-1 px-3 py-2 rounded-md border border-input bg-background text-sm font-mono"
                      />
                      <Button size="sm" onClick={() => copyToClipboard(deployLink)}>
                        {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                      </Button>
                    </div>
                  </>
                )}
              </div>
            </div>
          ) : (
            <div>
              <label className="text-sm font-medium">{t('keys.rename_label')}</label>
              <input
                type="text"
                value={newName}
                onChange={(e) => setNewName(e.target.value)}
                autoFocus
                placeholder="my-claude-code"
                className="w-full mt-1 h-10 px-3 rounded-md border border-input bg-background text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
              />
            </div>
          )}

          <DialogFooter>
            {createdKey ? (
              <Button onClick={() => setCreateDialogOpen(false)}>{t('common.done')}</Button>
            ) : (
              <>
                <Button variant="outline" onClick={() => setCreateDialogOpen(false)}>
                  {t('common.cancel')}
                </Button>
                <Button onClick={handleCreate} disabled={creating}>
                  {creating && <Loader2 className="w-4 h-4 mr-2 animate-spin" />}
                  {t('common.create')}
                </Button>
              </>
            )}
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Rename dialog */}
      <Dialog open={renameDialogOpen} onOpenChange={setRenameDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>{t('keys.rename_title')}</DialogTitle>
          </DialogHeader>
          <div>
            <label className="text-sm font-medium">{t('keys.rename_label')}</label>
            <input
              type="text"
              value={renameName}
              onChange={(e) => setRenameName(e.target.value)}
              autoFocus
              className="w-full mt-1 h-10 px-3 rounded-md border border-input bg-background text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
            />
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setRenameDialogOpen(false)}>
              {t('common.cancel')}
            </Button>
            <Button onClick={handleRename} disabled={saving}>
              {saving && <Loader2 className="w-4 h-4 mr-2 animate-spin" />}
              {t('common.save')}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Perm dialog */}
      <Dialog open={permDialogOpen} onOpenChange={setPermDialogOpen}>
        <DialogContent className="max-w-2xl">
          <DialogHeader>
            <DialogTitle>{t('keys.perm_title', { name: permTarget?.name || t('common.unnamed') })}</DialogTitle>
            <DialogDescription>{t('keys.perm_desc')}</DialogDescription>
          </DialogHeader>

          {modelsLoading ? (
            <div className="flex justify-center py-8">
              <Loader2 className="w-6 h-6 animate-spin text-muted-foreground" />
            </div>
          ) : permGroups.length === 0 ? (
            <p className="text-sm text-muted-foreground py-4">{t('keys.perm_no_models')}</p>
          ) : (
            <div className="max-h-[40vh] overflow-y-auto space-y-4 pr-2">
              {permGroups.map((g) => (
                <div key={g.name}>
                  <p className="text-xs font-medium text-muted-foreground mb-1.5">{g.name}</p>
                  <div className="grid grid-cols-2 md:grid-cols-3 gap-x-4 gap-y-1.5">
                    {g.models.map((m) => {
                      const checked = permSet.has(m);
                      return (
                        <label
                          key={m}
                          className="flex items-center gap-2 text-sm cursor-pointer select-none"
                        >
                          <input
                            type="checkbox"
                            checked={checked}
                            onChange={() => togglePerm(m)}
                            className="h-4 w-4 rounded border-input accent-primary"
                          />
                          <span className="font-mono text-xs truncate">{m}</span>
                        </label>
                      );
                    })}
                  </div>
                </div>
              ))}
            </div>
          )}

          <DialogFooter>
            <Button variant="outline" onClick={() => setPermDialogOpen(false)}>
              {t('common.cancel')}
            </Button>
            <Button onClick={handleSavePerms} disabled={saving}>
              {saving && <Loader2 className="w-4 h-4 mr-2 animate-spin" />}
              {t('common.save')}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Quota dialog */}
      <Dialog open={quotaDialogOpen} onOpenChange={setQuotaDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>{t('keys.quota_title', { name: quotaTarget?.name || t('common.unnamed') })}</DialogTitle>
            <DialogDescription>{t('keys.quota_desc')}</DialogDescription>
          </DialogHeader>
          <div className="space-y-4">
            <div>
              <label className="text-sm font-medium">{t('keys.quota_5h_label')}</label>
              <input
                type="number"
                min={0}
                value={quota5h}
                onChange={(e) => setQuota5h(e.target.value)}
                placeholder="0"
                className="w-full mt-1 h-10 px-3 rounded-md border border-input bg-background text-sm font-mono focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
              />
              <p className="text-xs text-muted-foreground mt-1">
                {t('keys.quota_preview', { value: formatAbbrev(parseInt(quota5h || '0', 10) || 0, t) })}
              </p>
            </div>
            <div>
              <label className="text-sm font-medium">{t('keys.quota_7d_label')}</label>
              <input
                type="number"
                min={0}
                value={quota7d}
                onChange={(e) => setQuota7d(e.target.value)}
                placeholder="0"
                className="w-full mt-1 h-10 px-3 rounded-md border border-input bg-background text-sm font-mono focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
              />
              <p className="text-xs text-muted-foreground mt-1">
                {t('keys.quota_preview', { value: formatAbbrev(parseInt(quota7d || '0', 10) || 0, t) })}
              </p>
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setQuotaDialogOpen(false)}>
              {t('common.cancel')}
            </Button>
            <Button onClick={handleSaveQuota} disabled={saving}>
              {saving && <Loader2 className="w-4 h-4 mr-2 animate-spin" />}
              {t('common.save')}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Delete dialog */}
      <Dialog open={deleteDialogOpen} onOpenChange={setDeleteDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>{t('keys.delete_title')}</DialogTitle>
            <DialogDescription>
              {t('keys.delete_confirm', { name: deleteTarget?.name || t('common.unnamed') })}
            </DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button variant="outline" onClick={() => setDeleteDialogOpen(false)}>
              {t('common.cancel')}
            </Button>
            <Button variant="destructive" onClick={confirmDelete}>
              {t('keys.delete_confirm_btn')}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
