// src/views/SettingsView.vue
<template>
  <div class="page">
    <div class="page__header">
      <h2 class="md-typescale-headline-medium page__title">{{ t('settings.title') }}</h2>
    </div>

    <md-tabs>
      <md-secondary-tab @click="activeTab = 0" :aria-selected="activeTab === 0"
        ><MdiIcon :path="mdiCogOutline" class="tab-icon" /> {{ t('settings.tab.general') }}</md-secondary-tab>
      <md-secondary-tab @click="activeTab = 1" :aria-selected="activeTab === 1"
        ><MdiIcon :path="mdiDirections" class="tab-icon" /> {{ t('settings.tab.routing') }}</md-secondary-tab>
      <md-secondary-tab @click="activeTab = 2" :aria-selected="activeTab === 2"
        ><MdiIcon :path="mdiDatabaseOutline" class="tab-icon" /> {{ t('settings.tab.data') }}</md-secondary-tab>
    </md-tabs>

    <!-- ========== 通用 TAB ========== -->
    <div v-show="activeTab === 0" class="tab-panel">
      <!-- 关于 -->
      <section class="card section">
        <div class="section__head">
          <span class="section__icon"><MdiIcon :path="mdiInformationOutline" /></span>
          <div>
            <h3 class="md-typescale-title-medium">{{ t('settings.about.title', { version: appVersion }) }}</h3>
            <p class="md-typescale-body-medium section__desc">{{ t('settings.about.desc') }}</p>
            <a class="section__link md-typescale-body-medium" :href="GITHUB_URL" @click.prevent="openExternal">
              <MdiIcon :path="mdiOpenInNew" />
              {{ t('settings.about.github') }}
            </a>
          </div>
        </div>
      </section>

      <!-- 语言 -->
      <section class="card section">
        <div class="section__head">
          <span class="section__icon"><MdiIcon :path="mdiTranslate" /></span>
          <div>
            <h3 class="md-typescale-title-medium">{{ t('settings.language.title') }}</h3>
            <p class="md-typescale-body-medium section__desc">{{ t('settings.language.desc') }}</p>
          </div>
        </div>
        <div class="section__body">
          <!-- no-checkmark：set 内部 grid-auto-columns:1fr 等宽列取内容最宽列，
               选中项的 checkmark 会推挤所有列宽；去掉后列宽由最长标签决定，稳定不跳动 -->
          <md-outlined-segmented-button-set>
            <md-outlined-segmented-button
              no-checkmark
              :selected="locale === 'zh-CN'"
              :label="t('settings.language.zh-CN')"
              @click="switchLocale('zh-CN')"
            ></md-outlined-segmented-button>
            <md-outlined-segmented-button
              no-checkmark
              :selected="locale === 'en'"
              :label="t('settings.language.en')"
              @click="switchLocale('en')"
            ></md-outlined-segmented-button>
          </md-outlined-segmented-button-set>
        </div>
      </section>

      <!-- 外观主题 -->
      <section class="card section">
        <div class="section__head">
          <span class="section__icon"><MdiIcon :path="mdiPalette" /></span>
          <div>
            <h3 class="md-typescale-title-medium">{{ t('settings.theme.title') }}</h3>
            <p class="md-typescale-body-medium section__desc">{{ t('settings.theme.desc') }}</p>
          </div>
        </div>
        <div class="section__body">
          <md-outlined-segmented-button-set>
            <md-outlined-segmented-button
              no-checkmark
              :selected="theme === 'system'"
              :label="t('settings.theme.system')"
              @click="chooseTheme('system')"
            ></md-outlined-segmented-button>
            <md-outlined-segmented-button
              no-checkmark
              :selected="theme === 'light'"
              :label="t('settings.theme.light')"
              @click="chooseTheme('light')"
            ></md-outlined-segmented-button>
            <md-outlined-segmented-button
              no-checkmark
              :selected="theme === 'dark'"
              :label="t('settings.theme.dark')"
              @click="chooseTheme('dark')"
            ></md-outlined-segmented-button>
          </md-outlined-segmented-button-set>
        </div>
        <div class="section__body hue-row">
          <span class="hue-label md-typescale-label-large">{{ t('settings.theme.hue') }}</span>
          <input
            type="range" min="0" max="360" step="1"
            :value="hue"
            class="hue-slider"
            @input="onHueInput"
          />
          <span class="hue-value mono">{{ hue }}°</span>
          <span class="hue-preview" :style="{ background: `hsl(${hue}, 50%, 42%)` }"></span>
          <md-text-button class="hue-reset" @click="resetHue">{{ t('settings.theme.hue_reset') }}</md-text-button>
        </div>
      </section>

      <!-- 开机静默启动 -->
      <section class="card section">
        <div class="section__head">
          <span class="section__icon"><MdiIcon :path="mdiPower" /></span>
          <div>
            <h3 class="md-typescale-title-medium">{{ t('settings.autostart.title') }}</h3>
            <p class="md-typescale-body-medium section__desc">{{ t('settings.autostart.desc') }}</p>
          </div>
        </div>
        <div class="section__body switch-row">
          <md-switch :selected="autostart" @change="toggleAutostart"></md-switch>
          <span class="md-typescale-body-medium switch-label">{{ autostart ? t('settings.autostart.on') : t('settings.autostart.off') }}</span>
        </div>
      </section>
    </div>

    <!-- ========== 路由 TAB ========== -->
    <div v-show="activeTab === 1" class="tab-panel">
      <section class="card section">
        <div class="section__head">
          <span class="section__icon"><MdiIcon :path="mdiSearchWeb" /></span>
          <div>
            <h3 class="md-typescale-title-medium">{{ t('settings.mcp_websearch.title') }}</h3>
            <p class="md-typescale-body-medium section__desc">{{ t('settings.mcp_websearch.desc') }}</p>
          </div>
        </div>
        <div class="section__body switch-row">
          <md-switch :selected="mcpWebsearch" @change="toggleMcpWebsearch"></md-switch>
          <span class="md-typescale-body-medium switch-label">{{ mcpWebsearch ? t('settings.mcp_websearch.on') : t('settings.mcp_websearch.off') }}</span>
        </div>
      </section>

      <!-- MCP WebFetch -->
      <section class="card section">
        <div class="section__head">
          <span class="section__icon"><MdiIcon :path="mdiWeb" /></span>
          <div>
            <h3 class="md-typescale-title-medium">{{ t('settings.mcp_webfetch.title') }}</h3>
            <p class="md-typescale-body-medium section__desc">{{ t('settings.mcp_webfetch.desc') }}</p>
          </div>
        </div>
        <div class="section__body switch-row">
          <md-switch :selected="mcpWebfetch" @change="toggleMcpWebfetch"></md-switch>
          <span class="md-typescale-body-medium switch-label">{{ mcpWebfetch ? t('settings.mcp_webfetch.on') : t('settings.mcp_webfetch.off') }}</span>
        </div>
      </section>

      <!-- MCP 接入信息 -->
      <section class="card section">
        <div class="section__head">
          <span class="section__icon"><MdiIcon :path="mdiLinkVariant" /></span>
          <div>
            <h3 class="md-typescale-title-medium">{{ t('settings.mcp_info.title') }}</h3>
            <p class="md-typescale-body-medium section__desc">{{ t('settings.mcp_info.desc') }}</p>
          </div>
        </div>
        <div class="section__body mcp-info">
          <div class="mcp-info__label md-typescale-label-large">{{ t('settings.mcp_info.endpoint') }}</div>
          <div class="key-box mono md-typescale-body-medium">{{ mcpEndpoint }}</div>
          <div class="mcp-info__label md-typescale-label-large">{{ t('settings.mcp_info.register') }}</div>
          <div class="key-box mono md-typescale-body-medium">{{ mcpRegisterCommand }}</div>
          <md-text-button @click="copyMcpCommand">
            <MdiIcon :path="mdiContentCopy" slot="icon" />
            {{ mcpCopied ? t('settings.mcp_info.copied') : t('settings.mcp_info.copy') }}
          </md-text-button>
        </div>
      </section>

      <!-- 故障转移 -->
      <section class="card section">
        <div class="section__head">
          <span class="section__icon"><MdiIcon :path="mdiSwapHorizontal" /></span>
          <div>
            <h3 class="md-typescale-title-medium">{{ t('settings.failover.title') }}</h3>
            <p class="md-typescale-body-medium section__desc">{{ t('settings.failover.desc') }}</p>
          </div>
        </div>
        <div class="section__body switch-row">
          <md-switch :selected="failover" @change="toggleFailover"></md-switch>
          <span class="md-typescale-body-medium switch-label">{{ failover ? t('settings.failover.on') : t('settings.failover.off') }}</span>
        </div>
      </section>
    </div>

    <!-- ========== 数据 TAB ========== -->
    <div v-show="activeTab === 2" class="tab-panel">
      <!-- 用户数据（导出 / 导入） -->
      <section class="card section">
        <div class="section__head">
          <span class="section__icon"><MdiIcon :path="mdiDatabaseSyncOutline" /></span>
          <div>
            <h3 class="md-typescale-title-medium">{{ t('settings.data.title') }}</h3>
            <p class="md-typescale-body-medium section__desc">{{ t('settings.data.desc') }}</p>
          </div>
        </div>
        <div class="section__body">
          <md-outlined-button @click="exportData" :disabled="dataBusy">
            <MdiIcon :path="mdiDownload" slot="icon" />
            {{ t('settings.data.export.button') }}
          </md-outlined-button>
          <md-outlined-button @click="importData" :disabled="dataBusy">
            <MdiIcon :path="mdiUpload" slot="icon" />
            {{ t('settings.data.import.button') }}
          </md-outlined-button>
        </div>
      </section>

      <!-- 重置 -->
      <section class="card section section--danger">
        <div class="section__head">
          <span class="section__icon"><MdiIcon :path="mdiDeleteForever" /></span>
          <div>
            <h3 class="md-typescale-title-medium">{{ t('settings.data.reset.title') }}</h3>
            <p class="md-typescale-body-medium section__desc">{{ t('settings.data.reset.desc') }}</p>
          </div>
        </div>
        <div class="section__body">
          <md-outlined-button class="danger-btn" @click="destroyOpen = true">
            <MdiIcon :path="mdiDeleteForever" slot="icon" />
            {{ t('settings.data.reset.button') }}
          </md-outlined-button>
        </div>
      </section>
    </div>

    <!-- 重置确认对话框 -->
    <md-dialog :open="destroyOpen" @close="destroyOpen = false">
      <div slot="headline">{{ t('settings.data.reset.title') }}</div>
      <div slot="content" class="dialog-content">
        <p class="md-typescale-body-medium">{{ t('settings.data.reset.confirm') }}</p>
      </div>
      <div slot="actions">
        <md-text-button @click="destroyOpen = false">{{ t('settings.cancel') }}</md-text-button>
        <md-text-button class="confirm-destroy" @click="confirmDestroy">{{ t('settings.confirm') }}</md-text-button>
      </div>
    </md-dialog>

    <!-- 导入确认对话框 -->
    <md-dialog :open="importOpen" @close="importOpen = false">
      <div slot="headline">{{ t('settings.data.import.title') }}</div>
      <div slot="content" class="dialog-content">
        <p class="md-typescale-body-medium">{{ t('settings.data.import.confirm') }}</p>
      </div>
      <div slot="actions">
        <md-text-button @click="importOpen = false">{{ t('settings.cancel') }}</md-text-button>
        <md-text-button @click="confirmImport">{{ t('settings.confirm') }}</md-text-button>
      </div>
    </md-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import '@material/web/tabs/tabs.js';
import '@material/web/tabs/secondary-tab.js';
import '@material/web/switch/switch.js';
import '@material/web/button/outlined-button.js';
import '@material/web/labs/segmentedbutton/outlined-segmented-button.js';
import '@material/web/labs/segmentedbuttonset/outlined-segmented-button-set.js';
import { useRouter } from 'vue-router';
import { getVersion } from '@tauri-apps/api/app';
import {
  mdiCogOutline, mdiDirections, mdiDatabaseOutline, mdiInformationOutline,
  mdiOpenInNew, mdiTranslate, mdiPalette, mdiPower, mdiSearchWeb, mdiWeb,
  mdiSwapHorizontal, mdiDatabaseSyncOutline, mdiDownload, mdiUpload,
  mdiDeleteForever, mdiLinkVariant, mdiContentCopy,
} from '@mdi/js';
import { settingsApi, dataApi, BASE_URL } from '../api';
import { getTheme, setTheme, getHue, setHue, type Theme } from '../theme';
import { open as openUrl } from '@tauri-apps/plugin-shell';
import { save, open } from '@tauri-apps/plugin-dialog';
import { readTextFile, writeTextFile } from '@tauri-apps/plugin-fs';
import { isEnabled, enable, disable } from '@tauri-apps/plugin-autostart';
import { t, setLocale, i18n } from '../i18n';
import type { Locale } from '../i18n';
import MdiIcon from '../components/MdiIcon.vue';

const router = useRouter();
const GITHUB_URL = 'https://github.com/wpy030414/xrl-router';

const appVersion = ref('—');
const destroyOpen = ref(false);
const importOpen = ref(false);
const activeTab = ref(0);
const dataBusy = ref(false);
const pendingImportSql = ref('');

async function openExternal() {
  try {
    await openUrl(GITHUB_URL);
  } catch {
    window.open(GITHUB_URL, '_blank');
  }
}

// ── 语言 ──
const locale = ref(i18n.locale);

function switchLocale(loc: Locale) {
  locale.value = loc;
  setLocale(loc);
}

// ── 主题 ──
const theme = ref<Theme>(getTheme());
const hue = ref(getHue());

function chooseTheme(t: Theme) {
  theme.value = t;
  setTheme(t);
}

function onHueInput(e: Event) {
  const val = Number((e.target as HTMLInputElement).value);
  hue.value = val;
  setHue(val);
}

function resetHue() {
  hue.value = 264;
  setHue(264);
}

// ── 开机自启 ──
const autostart = ref(false);

async function toggleAutostart() {
  const next = !autostart.value;
  autostart.value = next;
  try {
    if (next) {
      await enable();
    } else {
      await disable();
    }
  } catch {
    autostart.value = !next;
  }
}

// ── MCP WebSearch ──
const mcpWebsearch = ref(false);

async function toggleMcpWebsearch() {
  const next = !mcpWebsearch.value;
  mcpWebsearch.value = next;
  try {
    await settingsApi.update({ mcp_websearch: next });
  } catch {
    mcpWebsearch.value = !next;
  }
}

// ── MCP WebFetch ──
const mcpWebfetch = ref(false);

async function toggleMcpWebfetch() {
  const next = !mcpWebfetch.value;
  mcpWebfetch.value = next;
  try {
    await settingsApi.update({ mcp_webfetch: next });
  } catch {
    mcpWebfetch.value = !next;
  }
}

// ── MCP 接入信息 ──
const mcpEndpoint = `${BASE_URL}/mcp`;
const mcpRegisterCommand =
  `claude mcp add --transport http xrl-tools ${mcpEndpoint} ` +
  `--header "Authorization: Bearer <SERVICE_KEY>"`;
const mcpCopied = ref(false);

async function copyMcpCommand() {
  try {
    await navigator.clipboard.writeText(mcpRegisterCommand);
    mcpCopied.value = true;
    setTimeout(() => { mcpCopied.value = false; }, 2000);
  } catch {
    // ignore
  }
}

// ── 故障转移 ──
const failover = ref(false);

async function toggleFailover() {
  const next = !failover.value;
  failover.value = next;
  try {
    await settingsApi.update({ failover_enabled: next });
  } catch {
    failover.value = !next;
  }
}

// ── 数据导入/导出 ──
async function exportData() {
  dataBusy.value = true;
  try {
    const sql = await dataApi.export();
    const filePath = await save({
      defaultPath: `xrl-router-backup-${new Date().toISOString().slice(0, 10)}.sql`,
      filters: [{ name: 'SQL', extensions: ['sql'] }],
    });
    if (filePath) {
      await writeTextFile(filePath, sql);
    }
  } catch (e) {
    console.error('[Export] failed:', e);
  } finally {
    dataBusy.value = false;
  }
}

async function importData() {
  dataBusy.value = true;
  try {
    const filePath = await open({
      filters: [{ name: 'SQL', extensions: ['sql'] }],
      multiple: false,
    });
    if (filePath) {
      const sql = await readTextFile(filePath as string);
      pendingImportSql.value = sql;
      importOpen.value = true;
    }
  } catch (e) {
    console.error('[Import] file read failed:', e);
  } finally {
    dataBusy.value = false;
  }
}

async function confirmImport() {
  importOpen.value = false;
  try {
    await dataApi.import(pendingImportSql.value);
    pendingImportSql.value = '';
    // 导入成功后刷新页面以反映新数据
    window.location.reload();
  } catch (e) {
    console.error('[Import] failed:', e);
  }
}

// ── 重置 ──
async function confirmDestroy() {
  destroyOpen.value = false;
  try {
    await dataApi.reset();
  } catch {
    // ignore
  }
  localStorage.clear();
  router.push('/');
}

// ── 初始化 ──
onMounted(async () => {
  // 加载设置
  try {
    const s = await settingsApi.get();
    mcpWebsearch.value = !!s.mcp_websearch;
    mcpWebfetch.value = !!s.mcp_webfetch;
    failover.value = !!s.failover_enabled;
  } catch {
    // ignore
  }

  // 版本号
  try {
    appVersion.value = await getVersion();
  } catch {
    // 非 Tauri 环境
  }

  // 开机自启状态
  try {
    autostart.value = await isEnabled();
  } catch {
    // 非 Tauri 环境
  }
});
</script>

<style scoped>
.page__header { margin-bottom: 24px; }
.page__title { margin: 0; color: var(--md-sys-color-on-surface); }

/* Tabs */
md-tabs {
  margin-bottom: 20px;
}
md-secondary-tab {
  --md-secondary-tab-active-indicator-color: var(--md-sys-color-primary);
  --md-secondary-tab-active-focus-label-text-color: var(--md-sys-color-primary);
  --md-secondary-tab-active-pressed-label-text-color: var(--md-sys-color-primary);
}
.tab-icon { font-size: 18px; margin-right: 4px; vertical-align: -3px; }

.tab-panel { display: flex; flex-direction: column; gap: 16px; }

.section {
  background: var(--md-sys-color-surface-container-low);
  border-radius: var(--md-sys-shape-corner-medium);
  padding: 20px;
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.section__head { display: flex; align-items: flex-start; gap: 12px; }
.section__icon {
  width: 40px; height: 40px;
  border-radius: var(--md-sys-shape-corner-full);
  background: var(--md-sys-color-surface-container-high);
  color: var(--md-sys-color-on-surface-variant);
  display: flex; align-items: center; justify-content: center;
  font-size: 24px; flex-shrink: 0;
}
.section__head h3 { margin: 0; color: var(--md-sys-color-on-surface); }
.section__desc { margin: 2px 0 0; color: var(--md-sys-color-on-surface-variant); }

.section__link {
  display: inline-flex; align-items: center; gap: 6px;
  color: var(--md-sys-color-primary); text-decoration: none;
  margin-top: 2px;
}
.section__link:hover { text-decoration: underline; }

.section__body { display: flex; gap: 12px; align-items: center; flex-wrap: wrap; }
.section--danger .section__icon { background: var(--md-sys-color-error-container); color: var(--md-sys-color-on-error-container); }
.danger-btn { color: var(--md-sys-color-error); }

.switch-row { display: flex; align-items: center; gap: 12px; }
.switch-label { color: var(--md-sys-color-on-surface-variant); }

/* MCP 接入信息 */
.mcp-info { flex-direction: column; align-items: stretch; }
.mcp-info__label { color: var(--md-sys-color-on-surface-variant); margin-top: 4px; }
.mcp-info .key-box { word-break: break-all; user-select: text; }

.key-box {
  background: var(--md-sys-color-surface-container-high);
  border-radius: var(--md-sys-shape-corner-small);
  padding: 10px 12px;
}
.mono { font-family: 'Roboto Mono', ui-monospace, SFMono-Regular, Menlo, monospace; }

.confirm-destroy { color: var(--md-sys-color-error); }
.dialog-content { min-width: 320px; }

/* 令牌色滑块 */
.hue-row {
  display: flex; align-items: center; gap: 12px;
  padding-top: 8px;
  border-top: 1px solid var(--md-sys-color-outline-variant);
}
.hue-label {
  flex-shrink: 0;
  color: var(--md-sys-color-on-surface-variant);
  white-space: nowrap;
}
.hue-slider {
  flex: 1; min-width: 120px;
  -webkit-appearance: none; appearance: none;
  height: 12px;
  border-radius: 6px;
  background: linear-gradient(to right,
    hsl(0,50%,42%), hsl(60,50%,42%), hsl(120,50%,42%),
    hsl(180,50%,42%), hsl(240,50%,42%), hsl(300,50%,42%), hsl(360,50%,42%));
  outline: none;
  cursor: pointer;
}
.hue-slider::-webkit-slider-thumb {
  -webkit-appearance: none; appearance: none;
  width: 20px; height: 20px;
  border-radius: 50%;
  background: #fff;
  border: 3px solid var(--md-sys-color-primary);
  box-shadow: 0 1px 3px rgba(0,0,0,0.3);
  cursor: pointer;
}
.hue-slider::-moz-range-thumb {
  width: 20px; height: 20px;
  border-radius: 50%;
  background: #fff;
  border: 3px solid var(--md-sys-color-primary);
  box-shadow: 0 1px 3px rgba(0,0,0,0.3);
  cursor: pointer;
}
.hue-value {
  flex-shrink: 0;
  min-width: 40px; text-align: right;
  color: var(--md-sys-color-on-surface-variant);
  font-variant-numeric: tabular-nums;
}
.hue-preview {
  flex-shrink: 0;
  width: 24px; height: 24px;
  border-radius: var(--md-sys-shape-corner-full);
  box-shadow: inset 0 0 0 1px rgba(0,0,0,0.1);
}
.hue-reset {
  flex-shrink: 0;
  --md-sys-color-primary: var(--md-sys-color-on-surface-variant);
}
</style>

// src/views/SettingsView.tsx
import { useState, useEffect, useMemo } from 'react';
import {
  Palette,
  Globe,
  Moon,
  Sun,
  Monitor,
  Power,
  Search,
  FileText,
  Bell,
  Download,
  Upload,
  RotateCcw,
  Copy,
  Check,
  Loader2,
  Zap,
  Info,
  Database,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { useSettingsStore } from '@/stores/settings';
import { useTheme } from '@/hooks/useTheme';
import { useI18nStore, type Locale } from '@/i18n';
import { useT } from '@/i18n';
import { settingsApi, type AppSettings } from '@/lib/api';
import { tauriAutostart, tauriDialog, tauriFs, tauriShell, tauriApp, isTauri } from '@/lib/tauri';
import { cn } from '@/lib/utils';

type Tab = 'general' | 'routing' | 'data';

const TABS: { key: Tab; labelKey: string }[] = [
  { key: 'general', labelKey: 'settings.tab.general' },
  { key: 'routing', labelKey: 'settings.tab.routing' },
  { key: 'data', labelKey: 'settings.tab.data' },
];

export function SettingsView() {
  const t = useT();
  const { theme, hue, setTheme, setHue } = useTheme();
  const { locale, setLocale } = useI18nStore();
  const { settings, fetchSettings, updateSettings, loading } = useSettingsStore();

  const [activeTab, setActiveTab] = useState<Tab>('general');
  const [autostartEnabled, setAutostartEnabled] = useState(false);
  const [version, setVersion] = useState<string>('');
  const [saving, setSaving] = useState(false);
  const [resetDialogOpen, setResetDialogOpen] = useState(false);
  const [importDialogOpen, setImportDialogOpen] = useState(false);

  // Load settings and Tauri state
  useEffect(() => {
    const load = async () => {
      await fetchSettings();
      if (isTauri()) {
        const autoEnabled = await tauriAutostart.isEnabled();
        setAutostartEnabled(!!autoEnabled);
        const ver = await tauriApp.getVersion();
        if (ver) setVersion(ver);
      }
    };
    load();
  }, []);

  // Toggle handlers
  const handleSettingToggle = async (key: keyof AppSettings, value: boolean) => {
    setSaving(true);
    try {
      await updateSettings({ [key]: value });
    } finally {
      setSaving(false);
    }
  };

  const handleAutostartToggle = async () => {
    const newValue = !autostartEnabled;
    setAutostartEnabled(newValue);
    if (newValue) {
      await tauriAutostart.enable();
    } else {
      await tauriAutostart.disable();
    }
  };

  const handleThemeChange = async (newTheme: 'system' | 'light' | 'dark') => {
    setTheme(newTheme);
    await updateSettings({ theme: newTheme });
  };

  const handleHueChange = async (newHue: number) => {
    setHue(newHue);
    await updateSettings({ hue: newHue });
  };

  const handleLocaleChange = async (newLocale: Locale) => {
    setLocale(newLocale);
    await updateSettings({ locale: newLocale });
  };

  // Export
  const handleExport = async () => {
    try {
      const resp = await fetch('/api/data/export');
      if (!resp.ok) throw new Error('Export failed');
      const sql = await resp.text();

      if (isTauri()) {
        const path = await tauriDialog.save({
          title: 'Export Data',
          defaultPath: `xrl-router-backup-${new Date().toISOString().split('T')[0]}.sql`,
          filters: [{ name: 'SQL', extensions: ['sql'] }],
        });
        if (path) {
          await tauriFs.writeTextFile(path, sql);
        }
      } else {
        const blob = new Blob([sql], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `xrl-router-backup-${new Date().toISOString().split('T')[0]}.sql`;
        a.click();
        URL.revokeObjectURL(url);
      }
    } catch (e) {
      console.error('Export failed:', e);
    }
  };

  // Import
  const handleImport = async () => {
    try {
      let sql: string | null = null;
      if (isTauri()) {
        const path = await tauriDialog.open({
          title: 'Import Data',
          filters: [{ name: 'SQL', extensions: ['sql'] }],
        });
        if (path) {
          sql = await tauriFs.readTextFile(path);
        }
      } else {
        const input = document.createElement('input');
        input.type = 'file';
        input.accept = '.sql';
        input.onchange = async (e) => {
          const file = (e.target as HTMLInputElement).files?.[0];
          if (file) {
            sql = await file.text();
            await doImport(sql!);
          }
        };
        input.click();
        return;
      }
      if (sql) {
        await doImport(sql);
      }
    } catch (e) {
      console.error('Import failed:', e);
    }
    setImportDialogOpen(false);
  };

  const doImport = async (sql: string) => {
    const resp = await fetch('/api/data/import', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ sql }),
    });
    if (!resp.ok) throw new Error('Import failed');
    window.location.reload();
  };

  // Reset
  const handleReset = async () => {
    try {
      await fetch('/api/data/reset', { method: 'POST' });
      window.location.reload();
    } catch (e) {
      console.error('Reset failed:', e);
    }
    setResetDialogOpen(false);
  };

  // MCP endpoint info — always local, use 127.0.0.1 to avoid Tauri's tauri.localhost hostname
  const mcpEndpoint = 'http://127.0.0.1:19068/mcp';
  const mcpCmd = `claude mcp add --scope user --transport http xrl-router ${mcpEndpoint} --header "Authorization: Bearer <SERVICE_KEY>"`;
  const [copied, setCopied] = useState<'endpoint' | 'cmd' | null>(null);

  const handleCopyMcp = async (text: string, which: 'endpoint' | 'cmd') => {
    await navigator.clipboard.writeText(text);
    setCopied(which);
    setTimeout(() => setCopied(null), 2000);
  };

  // 令牌色色条：与 applyHue 同源（hsl(h 70% L)，L 取当前主题实际生效的亮度），
  // 每 30° 一个停靠点 —— 滑杆位置 h 处的颜色即真实应用的主题色。
  const hueBarLightness = useMemo(() => {
    const v = document.documentElement.style.getPropertyValue('--primary') || '';
    const l = v.trim().split(/\s+/)[2];
    return v.includes('70%') && /^\d+(\.\d+)?%$/.test(l || '') ? l : '45%';
  }, [theme]);
  const hueBar = `linear-gradient(to right, ${Array.from(
    { length: 13 },
    (_, i) => `hsl(${(i * 30) % 360} 70% ${hueBarLightness})`
  ).join(', ')})`;

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex justify-between items-start gap-4 flex-wrap">
        <h2 className="text-3xl font-normal m-0">{t('settings.title')}</h2>
      </div>

      {/* Tabs */}
      <div className="flex gap-2 border-b pb-2">
        {TABS.map((tab) => (
          <Button
            key={tab.key}
            variant={activeTab === tab.key ? 'default' : 'ghost'}
            size="sm"
            onClick={() => setActiveTab(tab.key)}
          >
            {t(tab.labelKey)}
          </Button>
        ))}
      </div>

      {/* General Tab */}
      {activeTab === 'general' && (
        <div className="space-y-6">
          {/* About */}
          <section className="space-y-2">
            <div className="flex items-center gap-2">
              <Info className="w-5 h-5" />
              <h3 className="text-lg font-semibold">{t('settings.about.title')}</h3>
            </div>
            {version && (
              <p className="text-sm text-muted-foreground">
                {t('settings.about.version', { version })}
              </p>
            )}
            <p className="text-sm text-muted-foreground">{t('settings.about.desc')}</p>
            <a
              href="https://github.com/wpy030414/xrl-router"
              target="_blank"
              rel="noopener noreferrer"
              className="text-sm text-primary hover:underline"
            >
              {t('settings.about.github')}
            </a>
          </section>

          {/* Language */}
          <section className="space-y-3">
            <div className="flex items-center gap-2">
              <Globe className="w-5 h-5" />
              <h3 className="text-lg font-semibold">{t('settings.language.title')}</h3>
            </div>
            <p className="text-sm text-muted-foreground">{t('settings.language.desc')}</p>
            <div className="flex gap-2">
              <Button
                variant={locale === 'zh-CN' ? 'default' : 'outline'}
                size="sm"
                onClick={() => handleLocaleChange('zh-CN')}
              >
                {t('settings.language.zh-CN')}
              </Button>
              <Button
                variant={locale === 'en' ? 'default' : 'outline'}
                size="sm"
                onClick={() => handleLocaleChange('en')}
              >
                {t('settings.language.en')}
              </Button>
            </div>
          </section>

          {/* Theme */}
          <section className="space-y-3">
            <div className="flex items-center gap-2">
              <Palette className="w-5 h-5" />
              <h3 className="text-lg font-semibold">{t('settings.theme.title')}</h3>
            </div>
            <p className="text-sm text-muted-foreground">{t('settings.theme.desc')}</p>
            <div className="flex gap-2 flex-wrap">
              <Button
                variant={theme === 'system' ? 'default' : 'outline'}
                size="sm"
                onClick={() => handleThemeChange('system')}
              >
                <Monitor className="w-4 h-4 mr-1" />
                {t('settings.theme.system')}
              </Button>
              <Button
                variant={theme === 'light' ? 'default' : 'outline'}
                size="sm"
                onClick={() => handleThemeChange('light')}
              >
                <Sun className="w-4 h-4 mr-1" />
                {t('settings.theme.light')}
              </Button>
              <Button
                variant={theme === 'dark' ? 'default' : 'outline'}
                size="sm"
                onClick={() => handleThemeChange('dark')}
              >
                <Moon className="w-4 h-4 mr-1" />
                {t('settings.theme.dark')}
              </Button>
            </div>

            {/* Hue slider */}
            <div className="space-y-2 pt-2">
              <label className="text-sm font-medium">{t('settings.theme.hue')}</label>
              <div className="flex items-center gap-3">
                {/* 圆角色条画在独立轨道层，input 透明浮在其上（保留滑杆交互）。
                    包装层用 flex 居中 input，避免 inline 行框基线留白造成的 3px 偏移 */}
                <div className="relative flex-1 flex items-center">
                  <div
                    aria-hidden
                    className="absolute inset-x-0 top-1/2 h-2 -translate-y-1/2 rounded-full"
                    style={{ background: hueBar }}
                  />
                  <input
                    type="range"
                    min="0"
                    max="360"
                    value={hue}
                    onChange={(e) => handleHueChange(parseInt(e.target.value))}
                    className="hue-slider relative w-full cursor-pointer"
                  />
                </div>
                <span className="text-sm font-mono w-10 text-right">{hue}</span>
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => handleHueChange(200)}
                >
                  {t('settings.theme.hue_reset')}
                </Button>
              </div>
            </div>
          </section>

          {/* Autostart (Tauri only) */}
          {isTauri() && (
            <section className="space-y-3">
              <div className="flex items-center gap-2">
                <Power className="w-5 h-5" />
                <h3 className="text-lg font-semibold">{t('settings.autostart.title')}</h3>
              </div>
              <p className="text-sm text-muted-foreground">{t('settings.autostart.desc')}</p>
              <button
                onClick={handleAutostartToggle}
                className={cn(
                  'relative inline-flex h-6 w-11 items-center rounded-full transition-colors',
                  autostartEnabled ? 'bg-primary' : 'bg-muted-foreground/20'
                )}
              >
                <span
                  className={cn(
                    'inline-block h-4 w-4 transform rounded-full bg-white transition-transform',
                    autostartEnabled ? 'translate-x-6' : 'translate-x-1'
                  )}
                />
              </button>
              <span className="text-sm ml-2">
                {autostartEnabled ? t('settings.autostart.on') : t('settings.autostart.off')}
              </span>
            </section>
          )}
        </div>
      )}

      {/* Routing Tab */}
      {activeTab === 'routing' && settings && (
        <div className="space-y-6">
          {/* Failover */}
          <section className="space-y-3">
            <div className="flex items-center gap-2">
              <Zap className="w-5 h-5" />
              <h3 className="text-lg font-semibold">{t('settings.failover.title')}</h3>
            </div>
            <p className="text-sm text-muted-foreground">{t('settings.failover.desc')}</p>
            <button
              onClick={() => handleSettingToggle('failover_enabled', !settings.failover_enabled)}
              className={cn(
                'relative inline-flex h-6 w-11 items-center rounded-full transition-colors',
                settings.failover_enabled ? 'bg-primary' : 'bg-muted-foreground/20'
              )}
            >
              <span
                className={cn(
                  'inline-block h-4 w-4 transform rounded-full bg-white transition-transform',
                  settings.failover_enabled ? 'translate-x-6' : 'translate-x-1'
                )}
              />
            </button>
            <span className="text-sm ml-2">
              {settings.failover_enabled ? t('settings.failover.on') : t('settings.failover.off')}
            </span>
          </section>

          {/* MCP Connection Info（在 MCP Tools 之上：先接入、再开关工具） */}
          <section className="space-y-3">
            <h3 className="text-lg font-semibold">{t('settings.mcp_info.title')}</h3>
            <p className="text-sm text-muted-foreground">{t('settings.mcp_info.desc')}</p>
            <div className="space-y-2">
              <label className="text-sm font-medium">{t('settings.mcp_info.endpoint')}</label>
              <div className="flex gap-2">
                <input
                  type="text"
                  readOnly
                  value={mcpEndpoint}
                  className="flex-1 px-3 py-2 rounded-md border border-input bg-background text-sm font-mono"
                />
                <Button size="sm" onClick={() => handleCopyMcp(mcpEndpoint, 'endpoint')}>
                  {copied === 'endpoint' ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                </Button>
              </div>
              {/* 注册命令与端点同等待遇：独立输入框 + 一键复制。
                  label 默认 inline，垂直 padding 不参与布局——须 block 才真正把间距撑开 */}
              <label className="block text-sm font-medium">{t('settings.mcp_info.register')}</label>
              <div className="flex gap-2">
                <input
                  type="text"
                  readOnly
                  value={mcpCmd}
                  className="flex-1 px-3 py-2 rounded-md border border-input bg-background text-sm font-mono"
                />
                <Button size="sm" onClick={() => handleCopyMcp(mcpCmd, 'cmd')}>
                  {copied === 'cmd' ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                </Button>
              </div>
            </div>
          </section>

          {/* MCP Tools */}
          <section className="space-y-3">
            <h3 className="text-lg font-semibold">MCP Tools</h3>

            {/* Web Search */}
            <div className="flex items-center justify-between py-3 border-b">
              <div className="flex items-center gap-2">
                <Search className="w-5 h-5" />
                <div>
                  <p className="font-medium">{t('settings.mcp_websearch.title')}</p>
                  <p className="text-sm text-muted-foreground">{t('settings.mcp_websearch.desc')}</p>
                </div>
              </div>
              <button
                onClick={() => handleSettingToggle('mcp_websearch', !settings.mcp_websearch)}
                className={cn(
                  'relative inline-flex h-6 w-11 items-center rounded-full transition-colors',
                  settings.mcp_websearch ? 'bg-primary' : 'bg-muted-foreground/20'
                )}
              >
                <span
                  className={cn(
                    'inline-block h-4 w-4 transform rounded-full bg-white transition-transform',
                    settings.mcp_websearch ? 'translate-x-6' : 'translate-x-1'
                  )}
                />
              </button>
            </div>

            {/* Web Fetch */}
            <div className="flex items-center justify-between py-3 border-b">
              <div className="flex items-center gap-2">
                <FileText className="w-5 h-5" />
                <div>
                  <p className="font-medium">{t('settings.mcp_webfetch.title')}</p>
                  <p className="text-sm text-muted-foreground">{t('settings.mcp_webfetch.desc')}</p>
                </div>
              </div>
              <button
                onClick={() => handleSettingToggle('mcp_webfetch', !settings.mcp_webfetch)}
                className={cn(
                  'relative inline-flex h-6 w-11 items-center rounded-full transition-colors',
                  settings.mcp_webfetch ? 'bg-primary' : 'bg-muted-foreground/20'
                )}
              >
                <span
                  className={cn(
                    'inline-block h-4 w-4 transform rounded-full bg-white transition-transform',
                    settings.mcp_webfetch ? 'translate-x-6' : 'translate-x-1'
                  )}
                />
              </button>
            </div>

            {/* Notify */}
            <div className="flex items-center justify-between py-3 border-b">
              <div className="flex items-center gap-2">
                <Bell className="w-5 h-5" />
                <div>
                  <p className="font-medium">{t('settings.mcp_notify.title')}</p>
                  <p className="text-sm text-muted-foreground">{t('settings.mcp_notify.desc')}</p>
                </div>
              </div>
              <button
                onClick={() => handleSettingToggle('mcp_notify', !settings.mcp_notify)}
                className={cn(
                  'relative inline-flex h-6 w-11 items-center rounded-full transition-colors',
                  settings.mcp_notify ? 'bg-primary' : 'bg-muted-foreground/20'
                )}
              >
                <span
                  className={cn(
                    'inline-block h-4 w-4 transform rounded-full bg-white transition-transform',
                    settings.mcp_notify ? 'translate-x-6' : 'translate-x-1'
                  )}
                />
              </button>
            </div>
          </section>
        </div>
      )}

      {/* Privacy Tab */}
      {activeTab === 'data' && (
        <div className="space-y-6">
          {/* Export/Import/Reset */}
          <section className="space-y-3">
            <div className="flex items-center gap-2">
              <Database className="w-5 h-5" />
              <h3 className="text-lg font-semibold">{t('settings.data.title')}</h3>
            </div>
            <p className="text-sm text-muted-foreground">{t('settings.data.desc')}</p>
            <div className="flex gap-3">
              <Button variant="outline" onClick={handleExport}>
                <Download className="w-4 h-4 mr-2" />
                {t('settings.data.export.button')}
              </Button>
              <Button onClick={() => setImportDialogOpen(true)}>
                <Upload className="w-4 h-4 mr-2" />
                {t('settings.data.import.button')}
              </Button>
              <Button variant="destructive" onClick={() => setResetDialogOpen(true)}>
                <RotateCcw className="w-4 h-4 mr-2" />
                {t('settings.data.reset.button')}
              </Button>
            </div>
          </section>
        </div>
      )}

      {/* Reset Confirmation Dialog */}
      <Dialog open={resetDialogOpen} onOpenChange={setResetDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>{t('settings.data.reset.title')}</DialogTitle>
            <DialogDescription>{t('settings.data.reset.confirm')}</DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button variant="outline" onClick={() => setResetDialogOpen(false)}>
              {t('settings.cancel')}
            </Button>
            <Button variant="destructive" onClick={handleReset}>
              {t('settings.confirm')}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Import Confirmation Dialog */}
      <Dialog open={importDialogOpen} onOpenChange={setImportDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>{t('settings.data.import.button')}</DialogTitle>
            <DialogDescription>{t('settings.data.import.confirm')}</DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button variant="outline" onClick={() => setImportDialogOpen(false)}>
              {t('settings.cancel')}
            </Button>
            <Button onClick={handleImport}>
              {t('settings.confirm')}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}

export default SettingsView;
