// src/views/StatsView.tsx
import { useState, useEffect, useMemo, useCallback, useRef } from 'react';
import {
  AreaChart,
  Area,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
} from 'recharts';
import { ChevronLeft, ChevronRight, ChevronDown, Inbox } from 'lucide-react';
import { Button } from '@/components/ui/button';
import {
  statsApi,
  requestLogApi,
  serviceKeysApi,
  type StatsRow,
  type TopModel,
  type RequestLogRow,
  type ServiceKey,
} from '@/lib/api';
import { useWebSocket } from '@/hooks/useWebSocket';
import { useT } from '@/i18n';
import { cn } from '@/lib/utils';

type TimeRange = 'today' | '1d' | '7d' | '30d';

const TIME_RANGES: { key: TimeRange; labelKey: string }[] = [
  { key: 'today', labelKey: 'stats.range.today' },
  { key: '1d', labelKey: 'stats.range.1d' },
  { key: '7d', labelKey: 'stats.range.7d' },
  { key: '30d', labelKey: 'stats.range.30d' },
];

/** 全数：千分位原样展示（总消耗磁贴主值）。 */
function formatTokens(num: number): string {
  return Math.round(num).toLocaleString();
}

/** 简略值：亿 / 万 结尾，保留 2 位小数（与 Vue 版一致）。 */
function formatTokensAuto(num: number, t: (key: string) => string): string {
  const yi = num / 1e8;
  if (yi >= 1) return `${yi.toFixed(2)}${t('stats.unit_yi')}`;
  const wan = num / 1e4;
  return `${wan.toFixed(2)}${t('stats.unit_wan')}`;
}

/** 后端 bucket 标签（h{epochHours} / d{epochDays}）→ 本地时间短标签，供 X 轴。 */
function formatBucket(label: string): string {
  const m = label.match(/^([hd])(\d+)$/);
  if (!m) return label;
  const step = m[1] === 'h' ? 3600 : 86400;
  // getTimezoneOffset() 返回分钟（UTC+8 = -480），转为秒并取负（与 Vue 版一致）
  const tzOffsetSec = -getTzOffset() * 60;
  const secs = parseInt(m[2], 10) * step - tzOffsetSec;
  const d = new Date(secs * 1000);
  if (m[1] === 'h') return `${String(d.getHours()).padStart(2, '0')}:00`;
  return `${d.getMonth() + 1}/${d.getDate()}`;
}

/** 长标签（tooltip）：小时桶 → M/D HH:00，天桶 → M/D。 */
function formatBucketLong(label: string): string {
  const m = label.match(/^([hd])(\d+)$/);
  if (!m) return label;
  const step = m[1] === 'h' ? 3600 : 86400;
  // getTimezoneOffset() 返回分钟（UTC+8 = -480），转为秒并取负（与 Vue 版一致）
  const tzOffsetSec = -getTzOffset() * 60;
  const secs = parseInt(m[2], 10) * step - tzOffsetSec;
  const d = new Date(secs * 1000);
  if (m[1] === 'h') return `${d.getMonth() + 1}/${d.getDate()} ${String(d.getHours()).padStart(2, '0')}:00`;
  return `${d.getMonth() + 1}/${d.getDate()}`;
}

/** Compute time range boundaries */
function getTimeBounds(range: TimeRange): { from: number; to: number; granularity: 'hour' | 'day' } {
  const now = new Date();
  let from: Date;
  let granularity: 'hour' | 'day';

  switch (range) {
    case 'today':
      from = new Date(now.getFullYear(), now.getMonth(), now.getDate());
      granularity = 'hour';
      break;
    case '1d':
      from = new Date(now.getTime() - 24 * 3600 * 1000);
      granularity = 'hour';
      break;
    case '7d':
      from = new Date(now.getTime() - 7 * 24 * 3600 * 1000);
      granularity = 'day';
      break;
    case '30d':
      from = new Date(now.getTime() - 30 * 24 * 3600 * 1000);
      granularity = 'day';
      break;
  }

  return {
    from: Math.floor(from.getTime() / 1000),
    to: Math.floor(now.getTime() / 1000),
    granularity,
  };
}

/** Get timezone offset in minutes */
function getTzOffset(): number {
  return new Date().getTimezoneOffset();
}

// ── Animated Stats Hook ──
// 数字翻动动画：与 Vue 版 useAnimatedNumber 同策略
// - requestAnimationFrame + easeOutSine 缓动，2400ms 内从旧值平滑翻动到新值
// - 缓存命中率基于动画中的 input/output/cache 值实时计算，而非直接用聚合值
interface AnimatedStats {
  totalTokens: number;
  totalRequests: number;
  totalInput: number;
  totalOutput: number;
  totalCache: number;
  cacheHitRate: string;
}

function useAnimatedStats(aggregated: {
  totalTokens: number;
  totalRequests: number;
  totalInput: number;
  totalOutput: number;
  totalCache: number;
}): AnimatedStats {
  const DURATION = 2400; // ms，与 Vue 版一致

  const totalTokensRef = useRef(0);
  const totalRequestsRef = useRef(0);
  const totalInputRef = useRef(0);
  const totalOutputRef = useRef(0);
  const totalCacheRef = useRef(0);

  const [display, setDisplay] = useState<AnimatedStats>({
    totalTokens: 0,
    totalRequests: 0,
    totalInput: 0,
    totalOutput: 0,
    totalCache: 0,
    cacheHitRate: '0.0',
  });

  const animationIdRef = useRef<number | null>(null);

  useEffect(() => {
    if (animationIdRef.current) {
      cancelAnimationFrame(animationIdRef.current);
    }

    const startTotalTokens = totalTokensRef.current;
    const startTotalRequests = totalRequestsRef.current;
    const startTotalInput = totalInputRef.current;
    const startTotalOutput = totalOutputRef.current;
    const startTotalCache = totalCacheRef.current;
    const startTime = performance.now();

    function tick(now: number) {
      const elapsed = now - startTime;
      const progress = Math.min(elapsed / DURATION, 1);
      // easeOutSine: 前 1/3 快速翻动，后 2/3 缓慢趋近目标值
      const ease = Math.sin(progress * Math.PI / 2);

      const curTotalTokens = Math.round(startTotalTokens + (aggregated.totalTokens - startTotalTokens) * ease);
      const curTotalRequests = Math.round(startTotalRequests + (aggregated.totalRequests - startTotalRequests) * ease);
      const curTotalInput = Math.round(startTotalInput + (aggregated.totalInput - startTotalInput) * ease);
      const curTotalOutput = Math.round(startTotalOutput + (aggregated.totalOutput - startTotalOutput) * ease);
      const curTotalCache = Math.round(startTotalCache + (aggregated.totalCache - startTotalCache) * ease);

      // 缓存命中率基于动画中的值实时计算（与 Vue 版一致）
      const base = curTotalInput + curTotalCache;
      const cacheHitRate = base > 0 ? ((curTotalCache / base) * 100).toFixed(1) : '0.0';

      totalTokensRef.current = curTotalTokens;
      totalRequestsRef.current = curTotalRequests;
      totalInputRef.current = curTotalInput;
      totalOutputRef.current = curTotalOutput;
      totalCacheRef.current = curTotalCache;

      setDisplay({
        totalTokens: curTotalTokens,
        totalRequests: curTotalRequests,
        totalInput: curTotalInput,
        totalOutput: curTotalOutput,
        totalCache: curTotalCache,
        cacheHitRate,
      });

      if (progress < 1) {
        animationIdRef.current = requestAnimationFrame(tick);
      }
    }

    animationIdRef.current = requestAnimationFrame(tick);

    return () => {
      if (animationIdRef.current) {
        cancelAnimationFrame(animationIdRef.current);
      }
    };
  }, [aggregated]);

  return display;
}

// ── Stat Tile Component ──
interface StatTileProps {
  label: string;
  value: string;
  sub?: string;
  className?: string;
}

function StatTile({ label, value, sub, className }: StatTileProps) {
  return (
    <div className={cn('rounded-xl border bg-card p-4 space-y-1', className)}>
      <div className="text-xs text-muted-foreground">{label}</div>
      <div className="text-xl font-semibold tabular-nums">
        {value}
        {/* 简略值衔在大数字之后（同行、小号、灰色），而非换行下方 */}
        {sub && (
          <span className="ml-1.5 text-xs font-normal text-muted-foreground">{sub}</span>
        )}
      </div>
    </div>
  );
}

// ── Custom Chart Tooltip ──
interface ChartTooltipProps {
  active?: boolean;
  payload?: Array<{ value: number; dataKey: string; color: string }>;
  label?: string;
}

function ChartTooltip({ active, payload, label }: ChartTooltipProps) {
  if (!active || !payload?.length) return null;

  return (
    <div className="rounded-lg border bg-popover p-3 shadow-md text-sm">
      <div className="font-medium mb-1.5">{formatBucketLong(String(label))}</div>
      {payload.map((entry, idx) => (
        <div key={idx} className="flex items-center gap-2 text-xs">
          <span
            className="w-2 h-2 rounded-full"
            style={{ backgroundColor: entry.color }}
          />
          <span className="text-muted-foreground">{entry.dataKey}:</span>
          <span className="font-medium tabular-nums">
            {(entry.value / 1000).toFixed(1)}K
          </span>
        </div>
      ))}
    </div>
  );
}

// ── Main View ──
export function StatsView() {
  const t = useT();
  const [timeRange, setTimeRange] = useState<TimeRange>('today');
  const [loading, setLoading] = useState(true);
  const [rows, setRows] = useState<StatsRow[]>([]);
  const [topModel, setTopModel] = useState<TopModel | null>(null);

  // 密钥筛选：作用于下方全部统计单元（磁贴 / 趋势图 / 请求日志）
  const [serviceKeys, setServiceKeys] = useState<ServiceKey[]>([]);
  const [keyFilter, setKeyFilter] = useState('');

  // Request log state
  const [logRows, setLogRows] = useState<RequestLogRow[]>([]);
  const [logTotal, setLogTotal] = useState(0);
  const [logPage, setLogPage] = useState(1);
  const [logLoading, setLogLoading] = useState(true);
  const LOG_PAGE_SIZE = 15;

  const fetchStats = async (range: TimeRange) => {
    const { from, to, granularity } = getTimeBounds(range);
    try {
      const result = await statsApi.query({
        from,
        to,
        granularity,
        // getTimezoneOffset() 返回分钟（UTC+8 = -480），转为秒并取负（与 Vue 版一致）
        tz_offset: -getTzOffset() * 60,
        service_key_id: keyFilter || undefined,
      });
      setRows(result.data || []);
      setTopModel(result.top_model || null);
    } catch (e: any) {
      console.error('Failed to fetch stats:', e);
    } finally {
      setLoading(false);
    }
  };

  const fetchLog = async (page: number) => {
    setLogLoading(true);
    try {
      // 与统计同源的时间范围：日志也跟随「当天/一天内/…」与密钥筛选
      const { from, to } = getTimeBounds(timeRange);
      const result = await requestLogApi.page({
        page,
        page_size: LOG_PAGE_SIZE,
        from,
        to,
        service_key_id: keyFilter || undefined,
      });
      setLogRows(result.data || []);
      setLogTotal(result.total);
    } catch (e: any) {
      console.error('Failed to fetch request log:', e);
    } finally {
      setLogLoading(false);
    }
  };

  // Real-time refresh via WebSocket
  useWebSocket('usage_stats_changed', useCallback(() => {
    // Debounce refresh
    fetchStats(timeRange);
  }, [timeRange, keyFilter]));

  // Load stats on range / key change；切换时间范围时日志回到第一页
  useEffect(() => {
    setLoading(true);
    fetchStats(timeRange);
    setLogPage(1);
  }, [timeRange, keyFilter]);

  // Load request log on page / key / range change
  useEffect(() => {
    fetchLog(logPage);
  }, [logPage, keyFilter, timeRange]);

  // 密钥筛选下拉数据
  useEffect(() => {
    serviceKeysApi.list().then(setServiceKeys).catch(() => {});
  }, []);

  // Computed aggregations
  const aggregated = useMemo(() => {
    const totalTokens = rows.reduce((sum, r) => sum + r.total_tokens, 0);
    const totalRequests = rows.reduce((sum, r) => sum + r.requests, 0);
    const totalInput = rows.reduce((sum, r) => sum + r.prompt_tokens, 0);
    const totalOutput = rows.reduce((sum, r) => sum + r.completion_tokens, 0);
    const totalCache = rows.reduce((sum, r) => sum + r.cache_read_input_tokens, 0);
    // 缓存命中率 = 命中 Tokens / (未命中输入 + 命中 Tokens)。
    // 后端把 prompt_tokens 拆为互斥的「未命中输入」与 cache_read_input_tokens，
    // 分母必须包含命中部分，否则会超过 100%（与 Vue 版算法一致）。
    const base = totalInput + totalCache;
    const cacheHitRate = base > 0 ? (totalCache / base) * 100 : 0;

    return { totalTokens, totalRequests, totalInput, totalOutput, totalCache, cacheHitRate };
  }, [rows]);

  // 数字翻动动画：与 Vue 版同策略，平滑过渡到新值
  const anim = useAnimatedStats(aggregated);

  // Chart data：生成完整的时间序列，没有数据的桶填0
  const chartData = useMemo(() => {
    const { from, to, granularity } = getTimeBounds(timeRange);
    const step = granularity === 'hour' ? 3600 : 86400;
    const prefix = granularity === 'hour' ? 'h' : 'd';
    // 后端 bucket = floor((utc_timestamp + tz_offset) / step)，前端也要加 tz_offset 才能匹配
    const tzOffsetSec = -getTzOffset() * 60; // getTimezoneOffset() 返回分钟（UTC+8 = -480），转为秒并取负

    // 生成完整的时间桶序列
    const start = Math.floor((from + tzOffsetSec) / step);
    const end = Math.floor((to + tzOffsetSec) / step);
    const buckets: string[] = [];
    for (let b = start; b <= end; b++) {
      buckets.push(`${prefix}${b}`);
    }

    // 把后端数据按 bucket 分组
    const dataMap = new Map<string, { input: number; output: number; cache: number }>();
    for (const r of rows) {
      const existing = dataMap.get(r.day) || { input: 0, output: 0, cache: 0 };
      existing.input += r.prompt_tokens;
      existing.output += r.completion_tokens;
      existing.cache += r.cache_read_input_tokens;
      dataMap.set(r.day, existing);
    }

    // 生成完整序列，没有数据的桶填0
    return buckets.map((bucket) => {
      const data = dataMap.get(bucket) || { input: 0, output: 0, cache: 0 };
      return {
        time: bucket,
        input: data.input,
        output: data.output,
        cache: data.cache,
      };
    });
  }, [rows, timeRange]);

  const logTotalPages = Math.max(1, Math.ceil(logTotal / LOG_PAGE_SIZE));

  // 键盘左右键翻页请求日志（仅在非输入焦点时生效）
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      // 输入框 / 下拉框聚焦时不拦截，避免影响正常输入
      const target = e.target as HTMLElement;
      if (target.tagName === 'INPUT' || target.tagName === 'TEXTAREA' || target.tagName === 'SELECT' || target.isContentEditable) {
        return;
      }
      if (e.key === 'ArrowLeft') {
        setLogPage((p) => Math.max(1, p - 1));
      } else if (e.key === 'ArrowRight') {
        setLogPage((p) => Math.min(logTotalPages, p + 1));
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [logTotalPages]);

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex justify-between items-start gap-4 flex-wrap">
        <h2 className="text-3xl font-normal m-0">{t('stats.title')}</h2>
        <div className="flex items-center gap-2.5">
          {/* 密钥筛选：作用于全部统计单元 */}
          <div className="relative">
            <select
              value={keyFilter}
              onChange={(e) => {
                setKeyFilter(e.target.value);
                setLogPage(1);
              }}
              className="h-9 appearance-none rounded-md border border-input bg-background pl-3 pr-8 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
            >
              <option value="">{t('common.all')}</option>
              {serviceKeys.map((k) => (
                <option key={k.id} value={k.id}>
                  {k.name} ({k.key_masked})
                </option>
              ))}
            </select>
            <ChevronDown className="pointer-events-none absolute right-2.5 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
          </div>
          <div className="flex gap-1 rounded-lg border bg-muted/50 p-1">
            {TIME_RANGES.map((r) => (
              <button
                key={r.key}
                onClick={() => setTimeRange(r.key)}
                className={cn(
                  'px-3 py-1.5 rounded-md text-sm font-medium transition-colors',
                  timeRange === r.key
                    ? 'bg-background shadow-sm text-foreground'
                    : 'text-muted-foreground hover:text-foreground'
                )}
              >
                {t(r.labelKey)}
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* Stat Tiles：第一行 总消耗(2列宽) + 调用最多模型 + 总请求次；第二行 输入/输出/命中/命中率 */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
        <StatTile
          label={t('stats.tile.total_tokens')}
          value={formatTokens(anim.totalTokens)}
          sub={`≈${formatTokensAuto(anim.totalTokens, t)}`}
          className="sm:col-span-2"
        />
        <StatTile
          label={t('stats.tile.top_model')}
          value={topModel?.model_name || '—'}
        />
        <StatTile
          label={t('stats.tile.total_requests')}
          value={formatTokens(anim.totalRequests)}
        />
        <StatTile
          label={t('stats.tile.input_tokens')}
          value={formatTokensAuto(anim.totalInput, t)}
        />
        <StatTile
          label={t('stats.tile.output_tokens')}
          value={formatTokensAuto(anim.totalOutput, t)}
        />
        <StatTile
          label={t('stats.tile.cache_tokens')}
          value={formatTokensAuto(anim.totalCache, t)}
        />
        <StatTile
          label={t('stats.tile.cache_hit_rate')}
          value={`${anim.cacheHitRate}%`}
        />
      </div>

      {/* Usage Trend Chart */}
      <div className="rounded-xl border bg-card p-5 space-y-3">
        <h3 className="text-sm font-medium">{t('stats.chart.title')}</h3>
        {loading ? (
          <div className="flex items-center justify-center h-[300px]">
            <div className="animate-spin rounded-full h-6 w-6 border-b-2 border-primary" />
          </div>
        ) : chartData.length === 0 ? (
          <div className="flex flex-col items-center justify-center h-[300px] text-muted-foreground">
            <Inbox className="w-8 h-8 mb-2" />
            <span className="text-sm">{t('common.empty')}</span>
          </div>
        ) : (
          <ResponsiveContainer width="100%" height={300}>
            <AreaChart data={chartData} margin={{ top: 10, right: 10, left: 0, bottom: 0 }}>
              <defs>
                <linearGradient id="colorInput" x1="0" y1="0" x2="0" y2="1">
                  <stop offset="5%" stopColor="hsl(217, 91%, 60%)" stopOpacity={0.3} />
                  <stop offset="95%" stopColor="hsl(217, 91%, 60%)" stopOpacity={0} />
                </linearGradient>
                <linearGradient id="colorOutput" x1="0" y1="0" x2="0" y2="1">
                  <stop offset="5%" stopColor="hsl(142, 71%, 45%)" stopOpacity={0.3} />
                  <stop offset="95%" stopColor="hsl(142, 71%, 45%)" stopOpacity={0} />
                </linearGradient>
                <linearGradient id="colorCache" x1="0" y1="0" x2="0" y2="1">
                  <stop offset="5%" stopColor="hsl(45, 93%, 47%)" stopOpacity={0.3} />
                  <stop offset="95%" stopColor="hsl(45, 93%, 47%)" stopOpacity={0} />
                </linearGradient>
              </defs>
              <CartesianGrid strokeDasharray="3 3" className="stroke-muted" />
              <XAxis
                dataKey="time"
                tick={{ fontSize: 11 }}
                tickLine={false}
                axisLine={false}
                className="text-muted-foreground"
                // 与 Vue 版同策略：bucket 转为本地时间短标签；点数超过容量时每 N 个显示一个
                tickFormatter={(v: string) => formatBucket(v)}
                interval={Math.max(0, Math.ceil(chartData.length / 7) - 1)}
              />
              <YAxis
                tick={{ fontSize: 11 }}
                tickLine={false}
                axisLine={false}
                tickFormatter={(v) => `${(Number(v) / 10000).toFixed(0)}`}
                className="text-muted-foreground"
              />
              <Tooltip content={<ChartTooltip />} />
              <Area
                type="monotone"
                dataKey="cache"
                stroke="hsl(45, 93%, 47%)"
                fill="url(#colorCache)"
                strokeWidth={2}
                name="Cache"
              />
              <Area
                type="monotone"
                dataKey="output"
                stroke="hsl(142, 71%, 45%)"
                fill="url(#colorOutput)"
                strokeWidth={2}
                name="Output"
              />
              <Area
                type="monotone"
                dataKey="input"
                stroke="hsl(217, 91%, 60%)"
                fill="url(#colorInput)"
                strokeWidth={2}
                name="Input"
              />
            </AreaChart>
          </ResponsiveContainer>
        )}
      </div>

      {/* Request Log */}
      <div className="rounded-xl border bg-card p-5 space-y-4">
        <div className="flex justify-between items-center">
          <h3 className="text-sm font-medium">
            {t('stats.log.title')}
            <span className="text-muted-foreground font-normal ml-2 text-xs">
              {t('stats.log.total', { total: logTotal })}
            </span>
          </h3>
        </div>

        {logRows.length === 0 ? (
          logLoading ? (
            <div className="flex items-center justify-center py-8">
              <div className="animate-spin rounded-full h-6 w-6 border-b-2 border-primary" />
            </div>
          ) : (
            <div className="flex flex-col items-center justify-center py-8 text-muted-foreground">
              <Inbox className="w-8 h-8 mb-2" />
              <span className="text-sm">{t('stats.log.empty')}</span>
            </div>
          )
        ) : (
          <>
            {/* 翻页时保留旧行半透明直至新页数据到达，避免表格高度塌缩导致页面跳顶 */}
            <div className={cn('overflow-x-auto transition-opacity', logLoading && 'opacity-50')}>
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b text-muted-foreground">
                    <th className="text-left py-2 px-2 font-medium">{t('stats.log.col_time')}</th>
                    <th className="text-left py-2 px-2 font-medium">{t('stats.log.col_key')}</th>
                    <th className="text-left py-2 px-2 font-medium">{t('stats.log.col_provider')}</th>
                    <th className="text-left py-2 px-2 font-medium">{t('stats.log.col_model')}</th>
                    <th className="text-right py-2 px-2 font-medium">{t('stats.log.col_input')}</th>
                    <th className="text-right py-2 px-2 font-medium">{t('stats.log.col_output')}</th>
                    <th className="text-center py-2 px-2 font-medium">{t('stats.log.col_status')}</th>
                  </tr>
                </thead>
                <tbody>
                  {logRows.map((row) => (
                    <tr key={row.id} className="border-b border-border/50 hover:bg-muted/30">
                      <td className="py-2 px-2 text-xs tabular-nums">
                        {new Date(row.timestamp * 1000).toLocaleString()}
                      </td>
                      <td className="py-2 px-2 text-xs truncate max-w-[120px]" title={row.service_key_name}>
                        {row.service_key_name || row.service_key_masked}
                      </td>
                      <td className="py-2 px-2 text-xs">{row.provider_name}</td>
                      <td className="py-2 px-2 text-xs truncate max-w-[150px]" title={row.model_display_name}>
                        {row.model_display_name}
                      </td>
                      <td className="py-2 px-2 text-xs text-right tabular-nums">
                        {row.prompt_tokens.toLocaleString()}
                      </td>
                      <td className="py-2 px-2 text-xs text-right tabular-nums">
                        {row.completion_tokens.toLocaleString()}
                      </td>
                      <td className="py-2 px-2 text-center">
                        <span
                          className={cn(
                            'inline-flex items-center px-1.5 py-0.5 rounded text-xs font-medium',
                            row.success
                              ? 'bg-green-500/10 text-green-600 dark:text-green-400'
                              : 'bg-red-500/10 text-red-600 dark:text-red-400'
                          )}
                          title={row.error_message || undefined}
                        >
                          {row.success ? t('stats.log.status_ok') : t('stats.log.status_fail')}
                        </span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            {/* Pagination */}
            <div className="flex items-center justify-between pt-2">
              <Button
                variant="outline"
                size="sm"
                disabled={logPage <= 1}
                onClick={() => setLogPage((p) => p - 1)}
              >
                <ChevronLeft className="w-4 h-4 mr-1" />
                {t('stats.log.prev')}
              </Button>
              <span className="text-sm text-muted-foreground">
                {t('stats.log.page', { current: logPage, total: logTotalPages })}
              </span>
              <Button
                variant="outline"
                size="sm"
                disabled={logPage >= logTotalPages}
                onClick={() => setLogPage((p) => p + 1)}
              >
                {t('stats.log.next')}
                <ChevronRight className="w-4 h-4 ml-1" />
              </Button>
            </div>
          </>
        )}
      </div>
    </div>
  );
}

export default StatsView;

// src/views/StatsView.vue
<template>
  <div class="page">
    <div class="page__header">
      <h2 class="md-typescale-headline-medium page__title">{{ t('stats.title') }}</h2>
      <div class="date-picker">
        <button class="date-btn" id="date-btn" @click="showPicker = true">
          <span class="mdi" :class="rangeIcon"></span>
          {{ rangeLabel }}
        </button>
        <md-menu :open="showPicker" anchor="date-btn" positioning="fixed" @closed="showPicker = false">
          <md-menu-item @click="setRange('today')"><span class="mdi mdi-calendar-today"></span> {{ t('stats.range.today') }}</md-menu-item>
          <md-menu-item @click="setRange('1d')"><span class="mdi mdi-calendar-range"></span> {{ t('stats.range.1d') }}</md-menu-item>
          <md-menu-item @click="setRange('7d')"><span class="mdi mdi-calendar-week"></span> {{ t('stats.range.7d') }}</md-menu-item>
          <md-menu-item @click="setRange('30d')"><span class="mdi mdi-calendar-month"></span> {{ t('stats.range.30d') }}</md-menu-item>
        </md-menu>
      </div>
    </div>

    <!-- 数据磁贴 -->
    <div class="tiles">
      <div class="tile tile--wide">
        <div class="tile__icon mdi mdi-counter"></div>
        <div class="tile__content">
          <div class="tile__label">{{ t('stats.tile.total_tokens') }}</div>
          <div class="tile__value tile__value--big">
            {{ formatTokens(animTotalTokens) }}<span class="tile__value-sub">≈{{ formatTokensAuto(animTotalTokens) }}</span>
          </div>
        </div>
      </div>
      <div class="tile">
        <div class="tile__icon mdi mdi-star"></div>
        <div class="tile__content">
          <div class="tile__label">{{ t('stats.tile.top_model') }}</div>
          <div class="tile__value">{{ topModelName }}</div>
        </div>
      </div>
      <div class="tile">
        <div class="tile__icon mdi mdi-api"></div>
        <div class="tile__content">
          <div class="tile__label">{{ t('stats.tile.total_requests') }}</div>
          <div class="tile__value">{{ formatTokens(animTotalRequests) }}</div>
        </div>
      </div>
      <div class="tile">
        <div class="tile__icon mdi mdi-arrow-down-bold"></div>
        <div class="tile__content">
          <div class="tile__label">{{ t('stats.tile.input_tokens') }}</div>
          <div class="tile__value">{{ formatTokensAuto(animTotalInputTokens) }}</div>
        </div>
      </div>
      <div class="tile">
        <div class="tile__icon mdi mdi-arrow-up-bold"></div>
        <div class="tile__content">
          <div class="tile__label">{{ t('stats.tile.output_tokens') }}</div>
          <div class="tile__value">{{ formatTokensAuto(animTotalOutputTokens) }}</div>
        </div>
      </div>
      <div class="tile">
        <div class="tile__icon mdi mdi-database-search"></div>
        <div class="tile__content">
          <div class="tile__label">{{ t('stats.tile.cache_tokens') }}</div>
          <div class="tile__value">{{ formatTokensAuto(animTotalCacheTokens) }}</div>
        </div>
      </div>
      <div class="tile">
        <div class="tile__icon mdi mdi-percent"></div>
        <div class="tile__content">
          <div class="tile__label">{{ t('stats.tile.cache_hit_rate') }}</div>
          <div class="tile__value">{{ animCacheHitRate }}%</div>
        </div>
      </div>
    </div>

    <div class="chart-container table-card">
      <div class="chart-card__header">
        <h3 class="md-typescale-title-medium">{{ t('stats.chart.title') }}</h3>
      </div>
      <div class="chart-body">
        <Line :data="chartData" :options="chartOptions" />
      </div>
    </div>

    <!-- 请求日志（分页，时间逆序） -->
    <div class="log-card table-card">
      <div class="log-card__header">
        <h3 class="md-typescale-title-medium">{{ t('stats.log.title') }}</h3>
        <span v-if="total > 0" class="log-card__total muted md-typescale-body-medium">{{ t('stats.log.total', { total }) }}</span>
      </div>

      <div v-if="!logRows.length" class="empty-state">
        <span class="mdi mdi-inbox-outline empty-state__icon"></span>
        <p class="md-typescale-body-large">{{ t('stats.log.empty') }}</p>
      </div>

      <div v-else>
        <div class="table-wrap">
          <table class="table">
            <thead>
              <tr class="md-typescale-label-large">
                <th>{{ t('stats.log.col_time') }}</th>
                <th>{{ t('stats.log.col_key') }}</th>
                <th>{{ t('stats.log.col_provider') }}</th>
                <th>{{ t('stats.log.col_model') }}</th>
                <th class="num-cell">{{ t('stats.log.col_input') }}</th>
                <th class="num-cell">{{ t('stats.log.col_output') }}</th>
                <th>{{ t('stats.log.col_status') }}</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="row in logRows" :key="row.id" class="md-typescale-body-medium">
                <td class="time-cell">{{ formatTime(row.timestamp) }}</td>
                <td class="key-cell" :title="row.service_key_name || ''">
                  <span class="mono">{{ row.service_key_name || '—' }}</span>
                  <span class="muted"> ({{ row.service_key_masked }})</span>
                </td>
                <td>{{ row.provider_name || '—' }}</td>
                <td class="model-cell" :title="row.model_display_name || ''">{{ row.model_display_name || '—' }}</td>
                <td class="num-cell mono">{{ row.prompt_tokens.toLocaleString() }}</td>
                <td class="num-cell mono">{{ row.completion_tokens.toLocaleString() }}</td>
                <td>
                  <span class="status-pill" :class="statusClass(row)" :title="row.error_message || ''">
                    {{ row.success ? t('stats.log.status_ok') : t('stats.log.status_fail') }}
                  </span>
                </td>
              </tr>
            </tbody>
          </table>
        </div>

        <div class="pagination">
          <md-outlined-button :disabled="page <= 1" @click="changePage(page - 1)">
            <span slot="icon" class="mdi mdi-chevron-left"></span>{{ t('stats.log.prev') }}
          </md-outlined-button>
          <span class="page-indicator md-typescale-body-medium">{{ t('stats.log.page', { current: page, total: totalPages }) }}</span>
          <md-outlined-button :disabled="page >= totalPages" @click="changePage(page + 1)">
            {{ t('stats.log.next') }}<span slot="icon" class="mdi mdi-chevron-right"></span>
          </md-outlined-button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted, watch } from 'vue';
import { Line } from 'vue-chartjs';
import {
  Chart as ChartJS, CategoryScale, LinearScale, PointElement, LineElement,
  Title, Tooltip, Legend, Filler
} from 'chart.js';
import { statsApi, requestLogApi, type RequestLogRow } from '../api';
import { wsClient } from '../ws';
import { t } from '../i18n';

ChartJS.register(CategoryScale, LinearScale, PointElement, LineElement, Title, Tooltip, Legend, Filler);

interface StatRow { key_id: string; key_label?: string; prompt_tokens: number; completion_tokens: number; cache_read_input_tokens?: number; total_tokens: number; requests: number; day: string; }
interface TopModel { model_id: string; model_name: string; prompt_tokens: number; completion_tokens: number; cache_read_input_tokens: number; total_tokens: number; requests: number; }
const data = ref<StatRow[]>([]);
const topModel = ref<TopModel | null>(null);
const rangeFrom = ref(0);
const rangeTo = ref(0);
const rangeGranularity = ref<'hour' | 'day'>('day');
// 系统本地时区偏移（秒），UTC+8 = 28800；用于把桶对齐到本地天/小时边界，而非 UTC。
const tzOffset = -new Date().getTimezoneOffset() * 60;

// X 轴始终是所选范围内的完整连续序列（按当前粒度分桶，与后端一致），
// 无数据的桶也保留并填 0 —— 否则真实用量稀疏时坐标轴会出现空洞或停在最后一条记录。
const dates = computed(() => {
  if (!rangeFrom.value || !rangeTo.value) return [];
  const step = rangeGranularity.value === 'hour' ? 3600 : 86400;
  const prefix = rangeGranularity.value === 'hour' ? 'h' : 'd';
  const start = Math.floor((rangeFrom.value + tzOffset) / step);
  const end = Math.floor((rangeTo.value + tzOffset) / step);
  const out: string[] = [];
  for (let b = start; b <= end; b++) out.push(`${prefix}${b}`);
  return out;
});
// 真实出现过的服务密钥去重，用作图例系列；无数据时为空，图表显示空白。
const keys = computed(() => [...new Set(data.value.map(d => d.key_id || ''))].filter(Boolean).sort());
// key_id -> 可读标签（密钥名 + 掩码），后端已 JOIN api_keys 给出；用于图例显示。
const keyLabelMap = computed(() => {
  const m: Record<string, string> = {};
  for (const d of data.value) {
    if (d.key_id && !(d.key_id in m)) m[d.key_id] = d.key_label || d.key_id;
  }
  return m;
});

// Build per-key-per-model data for hover drilldown
const drillData = computed(() => {
  const map: Record<string, Record<string, number>> = {};
  for (const row of data.value) {
    const kid = row.key_id || '(all)';
    if (!map[`${row.day}|${kid}`]) map[`${row.day}|${kid}`] = {};
    map[`${row.day}|${kid}`]['total'] = (map[`${row.day}|${kid}`]['total'] || 0) + row.total_tokens;
  }
  return map;
});

function mdVar(name: string): string {
  return getComputedStyle(document.documentElement).getPropertyValue(name).trim();
}

const chartData = computed(() => {
  const colors = [
    mdVar('--md-sys-color-primary') || '#6750A4',
    mdVar('--md-sys-color-error') || '#B3261E',
    mdVar('--md-sys-color-tertiary') || '#7D5260',
    mdVar('--md-sys-color-secondary') || '#625B71',
    mdVar('--md-sys-color-tertiary') || '#7D5260',
    mdVar('--md-sys-color-inverse-primary') || '#D0BCFF',
  ];
  const datasets = keys.value.map((kid, i) => ({
    label: keyLabelMap.value[kid] || kid,
    data: dates.value.map(day => {
      const t = data.value.filter(d => d.day === day && d.key_id === kid).reduce((s, d) => s + d.total_tokens, 0);
      return t; // raw total tokens, display as 万 in tooltip only
    }),
    borderColor: colors[i % colors.length],
    backgroundColor: colors[i % colors.length] + '20',
    fill: false,
    tension: 0.35,
    spanGaps: true,
    pointRadius: 2,
    pointHoverRadius: 6,
  }));
  return { labels: dates.value, datasets };
});

const chartOptions = computed(() => ({
  responsive: true,
  maintainAspectRatio: false,
  interaction: { mode: 'index' as const, intersect: false },
  plugins: {
    legend: { position: 'bottom' as const, labels: { usePointStyle: true, padding: 16, font: { family: "'PingFang SC', system-ui, sans-serif", size: 12 } } },
    tooltip: {
      callbacks: {
        title: function (ctx: any) {
          const label = ctx[0]?.label || '';
          return formatBucketLong(label);
        },
        label: function (ctx: any) {
          const kidLabel = ctx.dataset.label;
          const raw = Number(ctx.raw);
          return t('stats.tooltip.unit', { value: (raw / 10000).toFixed(1) });
        },
        afterBody: function (ctx: any) {
          const day = ctx[0]?.label;
          const kidLabel = ctx[0]?.dataset?.label || '';
          const kid = keys.value.find(k => (keyLabelMap.value[k] || k) === kidLabel) || '';
          const dayData = data.value.filter(d => d.day === day && d.key_id === kid);
          if (dayData.length === 0) return [];
          const lines: string[] = [t('stats.tooltip.distribution')];
          for (const d of dayData) {
            const cacheR = (d.cache_read_input_tokens || 0) / 10000;
            const input = (d.prompt_tokens / 10000).toFixed(1);
            const output = (d.completion_tokens / 10000).toFixed(1);
            let line = t('stats.tooltip.total', { total: (d.total_tokens / 10000).toFixed(1), input, output });
            if (cacheR > 0.05) {
              line += t('stats.tooltip.cache_read', { value: cacheR.toFixed(1) });
            }
            line += ')';
            lines.push(line);
          }
          return lines;
        }
      }
    }
  },
  scales: {
    x: {
      grid: { display: false },
      title: { display: true, text: t('stats.chart.x_axis'), font: { family: "'PingFang SC', system-ui, sans-serif", size: 12 } },
      ticks: {
        font: { family: "'PingFang SC', system-ui, sans-serif", size: 10 },
        maxTicksLimit: 7,
        callback: function(_value: any, index: number) {
          const dayCount = dates.value.length;
          // Longer ranges: show every Nth label so they don't overlap.
          if (dayCount > 7) {
            const step = Math.ceil(dayCount / 7);
            if (index % step !== 0) return '';
          }
          const label = dates.value[index];
          return label ? formatBucket(label) : '';
        }
      }
    },
    y: {
      beginAtZero: true,
      min: 0,
      title: { display: true, text: t('stats.chart.y_axis'), font: { family: "'PingFang SC', system-ui, sans-serif", size: 12 } },
      ticks: {
        font: { family: "'PingFang SC', system-ui, sans-serif", size: 10 },
        maxTicksLimit: 6,
        callback: function(value: any) { return (Number(value) / 10000).toFixed(0); }
      }
    }
  }
}));

// Date range
const range = ref<'today' | '1d' | '7d' | '30d'>('today');
const showPicker = ref(false);

const rangeIcon = computed(() => {
  if (range.value === 'today') return 'mdi-calendar-today';
  if (range.value === '1d') return 'mdi-calendar-range';
  if (range.value === '7d') return 'mdi-calendar-week';
  return 'mdi-calendar-month';
});

const rangeLabel = computed(() => {
  if (range.value === 'today') return t('stats.range.today');
  if (range.value === '1d') return t('stats.range.1d');
  if (range.value === '7d') return t('stats.range.7d');
  return t('stats.range.30d');
});

function setRange(r: 'today' | '1d' | '7d' | '30d') {
  range.value = r;
  showPicker.value = false;
  fetchStats();
}

const customFrom = ref('');
const customTo = ref('');

async function fetchStats() {
  const now = Math.floor(Date.now() / 1000);
  let granularity: 'hour' | 'day';
  if (range.value === 'today') {
    // 从今日 0 点（含）到现在，按小时分桶
    const dayNow = Math.floor((now + tzOffset) / 86400);
    rangeFrom.value = dayNow * 86400 - tzOffset;
    rangeTo.value = now;
    granularity = 'hour';
  } else if (range.value === '1d') {
    // 24 个小时桶，最右刻度 = 当前小时桶的起始（如 01:49 → 最右刻度 01:00）；
    // 当前小时数据查到 now，落在最右桶内。
    const hourNow = Math.floor((now + tzOffset) / 3600);
    rangeTo.value = hourNow * 3600 - tzOffset;
    rangeFrom.value = rangeTo.value - 23 * 3600;
    granularity = 'hour';
  } else {
    // N 个天桶，最右刻度 = 当天 0 点（如 7/31 → 最右刻度 7/31）；
    // 当天数据查到 now，落在最右桶内。
    const days = range.value === '7d' ? 7 : 30;
    const dayNow = Math.floor((now + tzOffset) / 86400);
    rangeTo.value = dayNow * 86400 - tzOffset;
    rangeFrom.value = rangeTo.value - (days - 1) * 86400;
    granularity = 'day';
  }
  rangeGranularity.value = granularity;
  try {
    const json = await statsApi.query({ from: rangeFrom.value, to: now, granularity, tz_offset: tzOffset });
    data.value = json?.data ?? [];
    topModel.value = json?.top_model ?? null;
  } catch {
    data.value = [];
    topModel.value = null;
  }
}

// 磁贴聚合：基于当前所选时间范围，对所有桶求和
const totalTokens = computed(() => data.value.reduce((s, d) => s + d.total_tokens, 0));
const totalInputTokens = computed(() => data.value.reduce((s, d) => s + d.prompt_tokens, 0));
const totalOutputTokens = computed(() => data.value.reduce((s, d) => s + d.completion_tokens, 0));
const totalCacheTokens = computed(() => data.value.reduce((s, d) => s + (d.cache_read_input_tokens || 0), 0));
const totalRequests = computed(() => data.value.reduce((s, d) => s + d.requests, 0));
// 缓存命中率 = 命中 Tokens / (未缓存输入 + 命中 Tokens)
// 后端将 prompt_tokens 拆为「未命中输入」与 cache_read_input_tokens（命中），
// 两者互斥且相加才是全部输入，因此分母必须包含命中部分，否则会 >100%。
const cacheHitRate = computed(() => {
  const input = totalInputTokens.value + totalCacheTokens.value;
  if (input <= 0) return '0.0';
  return ((totalCacheTokens.value / input) * 100).toFixed(1);
});
const topModelName = computed(() => topModel.value?.model_name || '—');

// 数字翻动动画：平滑过渡到新值
function useAnimatedNumber(source: () => number) {
  const displayed = ref(0);
  let animationId: number | null = null;
  const DURATION = 2400; // ms

  watch(source, (newVal) => {
    if (animationId) cancelAnimationFrame(animationId);
    const startVal = displayed.value;
    const startTime = performance.now();

    function tick(now: number) {
      const elapsed = now - startTime;
      const progress = Math.min(elapsed / DURATION, 1);
      // easeOutSine: 前 1/3 快速翻动，后 2/3 缓慢趋近目标值
      const ease = Math.sin(progress * Math.PI / 2);
      displayed.value = Math.round(startVal + (newVal - startVal) * ease);
      if (progress < 1) {
        animationId = requestAnimationFrame(tick);
      }
    }
    animationId = requestAnimationFrame(tick);
  }, { immediate: true });

  return displayed;
}

const animTotalTokens = useAnimatedNumber(() => totalTokens.value);
const animTotalInputTokens = useAnimatedNumber(() => totalInputTokens.value);
const animTotalOutputTokens = useAnimatedNumber(() => totalOutputTokens.value);
const animTotalCacheTokens = useAnimatedNumber(() => totalCacheTokens.value);
const animTotalRequests = useAnimatedNumber(() => totalRequests.value);

// 缓存命中率动画（保留1位小数）
const animCacheHitRate = computed(() => {
  const input = animTotalInputTokens.value + animTotalCacheTokens.value;
  if (input <= 0) return '0.0';
  return ((animTotalCacheTokens.value / input) * 100).toFixed(1);
});

// 总消耗 Tokens：不换算，直接显示整数（带千位分隔符）
function formatTokens(n: number): string {
  return Math.round(n).toLocaleString();
}
// 输入/输出/命中：自动以万/K、亿/B 结尾，保留 2 位小数
function formatTokensAuto(n: number): string {
  const yi = n / 1e8;
  if (yi >= 1) return `${yi.toFixed(2)}${t('stats.unit_yi')}`;
  const wan = n / 1e4;
  return `${wan.toFixed(2)}${t('stats.unit_wan')}`;
}

function formatBucket(label: string): string {
  const m = label.match(/^([hd])(\d+)$/);
  if (!m) return label;
  const step = m[1] === 'h' ? 3600 : 86400;
  const secs = parseInt(m[2]) * step - tzOffset;
  const d = new Date(secs * 1000);
  if (m[1] === 'h') return `${String(d.getHours()).padStart(2, '0')}:00`;
  return `${d.getMonth() + 1}/${d.getDate()}`;
}

function formatBucketLong(label: string): string {
  const m = label.match(/^([hd])(\d+)$/);
  if (!m) return label;
  const step = m[1] === 'h' ? 3600 : 86400;
  const secs = parseInt(m[2]) * step - tzOffset;
  const d = new Date(secs * 1000);
  if (m[1] === 'h') return `${d.getMonth() + 1}/${d.getDate()} ${String(d.getHours()).padStart(2, '0')}:00`;
  return `${d.getMonth() + 1}/${d.getDate()}`;
}

// 后端每 5s 通过 WS 推送 usage_stats_changed；收到后用当前参数重新拉取。
function onStatsChanged() {
  fetchStats();
  fetchLogs();
}

// ── 请求日志（分页，时间逆序） ──
const logRows = ref<RequestLogRow[]>([]);
const page = ref(1);
const pageSize = 10;
const total = ref(0);
const totalPages = computed(() => Math.max(1, Math.ceil(total.value / pageSize)));

async function fetchLogs() {
  try {
    const json = await requestLogApi.page({ page: page.value, page_size: pageSize });
    total.value = json.total;
    logRows.value = json.data;
    // 数据收缩（或新行把旧页挤出）导致当前页越界 → 回退最后一页重取，避免空白页
    const maxPage = Math.max(1, Math.ceil(json.total / pageSize));
    if (json.data.length === 0 && page.value > 1) {
      page.value = maxPage;
      await fetchLogs();
    }
  } catch {
    // 静默失败，保留旧内容
  }
}

function changePage(p: number) {
  page.value = p;
  fetchLogs();
}

/** 状态 pill 着色：成功绿 / 失败红 */
function statusClass(row: RequestLogRow): string {
  return row.success ? 'status--ok' : 'status--fail';
}

/** 本地时间 YYYY-MM-DD HH:mm */
function formatTime(tSec: number): string {
  const d = new Date(tSec * 1000);
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')} ${String(d.getHours()).padStart(2, '0')}:${String(d.getMinutes()).padStart(2, '0')}`;
}

onMounted(() => {
  fetchStats();
  fetchLogs();
  wsClient.connect();
  wsClient.on('usage_stats_changed', onStatsChanged);
});

onUnmounted(() => {
  wsClient.off('usage_stats_changed', onStatsChanged);
});
</script>

<style scoped>
.page__header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 24px; gap: 16px; flex-wrap: wrap; }
.page__title { margin: 0; }
.date-picker { position: relative; }
.date-btn {
  display: inline-flex; align-items: center; gap: 8px;
  height: 40px; padding: 0 20px;
  border: 1px solid var(--md-sys-color-outline);
  border-radius: var(--md-sys-shape-corner-full);
  background: transparent;
  color: var(--md-sys-color-on-surface);
  font-family: inherit; font-size: 0.875rem; font-weight: 500;
  cursor: pointer;
  transition: background 150ms;
}
.date-btn:hover { background: var(--md-sys-color-surface-container-high); }

/* 数据磁贴网格：4 列，不足 4 列的自动换行 */
.tiles {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 12px;
  margin-bottom: 16px;
}
.tile {
  display: flex; align-items: center; gap: 12px;
  padding: 12px 16px;
  background: var(--md-sys-color-surface-container-low);
  border-radius: var(--md-sys-shape-corner-medium);
  border: 1px solid var(--md-sys-color-outline-variant, rgba(0,0,0,0.08));
  min-height: 64px;
}
.tile__icon {
  font-size: 22px;
  color: var(--md-sys-color-primary);
  flex-shrink: 0;
}
.tile__content { display: flex; flex-direction: column; gap: 2px; min-width: 0; }
.tile__label {
  font-size: 0.75rem;
  color: var(--md-sys-color-on-surface-variant);
  letter-spacing: 0.02em;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
.tile__value {
  font-size: 1.1rem;
  font-weight: 600;
  color: var(--md-sys-color-on-surface);
  font-variant-numeric: tabular-nums;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
/* 总消耗 Tokens：大数字 + 小号换算后缀 */
.tile__value--big {
  font-size: 2rem;
  line-height: 1.2;
}
.tile__value-sub {
  margin-left: 8px;
  font-size: 0.8rem;
  font-weight: 400;
  color: var(--md-sys-color-on-surface-variant);
  vertical-align: 0.25em;
}
/* 总消耗 Tokens 独占两列 */
.tile--wide { grid-column: span 2; }

@media (max-width: 900px) {
  .tiles { grid-template-columns: repeat(2, 1fr); }
  .tile--wide { grid-column: span 2; }
}
@media (max-width: 520px) {
  .tiles { grid-template-columns: 1fr; }
  .tile--wide { grid-column: span 1; }
}

.chart-container { padding: 24px; background: var(--md-sys-color-surface-container-low); border-radius: var(--md-sys-shape-corner-medium); height: 440px; display: flex; flex-direction: column; }
.chart-card__header h3 { margin: 0 0 12px; color: var(--md-sys-color-on-surface); }
.chart-body { flex: 1; min-height: 0; }
.chart-container canvas { max-height: 100% !important; }

.empty-state { display: flex; flex-direction: column; align-items: center; gap: 8px; padding: 64px 24px; text-align: center; }
.empty-state__icon { font-size: 48px; color: var(--md-sys-color-on-surface-variant); }

.table-card { background: var(--md-sys-color-surface-container-low); border-radius: var(--md-sys-shape-corner-medium); }

/* ── 请求日志 ── */
.log-card { margin-top: 16px; padding: 24px; }
.log-card__header { display: flex; align-items: baseline; gap: 8px; margin-bottom: 12px; }
.log-card__header h3 { margin: 0; color: var(--md-sys-color-on-surface); }
.log-card__total { margin-left: auto; }
.table-wrap { overflow-x: auto; }
.table { border-collapse: collapse; table-layout: auto; width: 100%; min-width: 720px; }
.table th { text-align: left; padding: 10px 12px; color: var(--md-sys-color-on-surface-variant); vertical-align: middle; white-space: nowrap; }
.table td { padding: 10px 12px; vertical-align: middle; white-space: nowrap; }
.table tr { border-bottom: 1px solid var(--md-sys-color-outline-variant); }
.table tr:last-child { border-bottom: none; }
.time-cell { color: var(--md-sys-color-on-surface-variant); font-size: 0.8rem; }
.key-cell { max-width: 180px; overflow: hidden; text-overflow: ellipsis; }
.model-cell { max-width: 220px; overflow: hidden; text-overflow: ellipsis; }
.num-cell { text-align: right; font-variant-numeric: tabular-nums; }
.muted { color: var(--md-sys-color-on-surface-variant); }
.mono { font-family: 'Roboto Mono', monospace; font-size: 0.85rem; }

.status-pill {
  display: inline-block; padding: 2px 10px; border-radius: var(--md-sys-shape-corner-full);
  font-size: 0.75rem; font-weight: 500;
}
.status--ok {
  color: var(--md-sys-color-openai-brand);
  background: color-mix(in srgb, var(--md-sys-color-openai-brand) 15%, transparent);
}
.status--fail {
  color: var(--md-sys-color-error);
  background: var(--md-sys-color-error-container);
}

.pagination { display: flex; align-items: center; justify-content: flex-end; gap: 12px; margin-top: 16px; }
.page-indicator { color: var(--md-sys-color-on-surface-variant); }
</style>
